### ISSUE TITLE
Incorrect slider accuracy

### ISSUE THREAD

**Issue by ALVAROPING1** [Wieku/danser-go#102]
**Describe the bug**
The sliders at `0:56:965` and `1:01:915` incorrectly show the slider end being missed when the replay is played in danser, but they aren't missed when the replay is played in osu!

Replay file: [Alvaroping1 - HO-KAGO TEA TIME - Kira Kira Days [Kowari's Extra!] (2021-04-28) Osu.zip](https://github.com/Wieku/danser-go/files/6399350/Alvaroping1.-.HO-KAGO.TEA.TIME.-.Kira.Kira.Days.Kowari.s.Extra.2021-04-28.Osu.zip)

**Screenshots**
Danser's output: https://user-images.githubusercontent.com/43814863/116566742-4d333980-a907-11eb-8264-18054ccdebd2.mp4
osu!'s output: https://user-images.githubusercontent.com/43814863/116566949-79e75100-a907-11eb-9f35-a4ac19168174.mp4

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6399386/danser.log)

**Computer configuration:**
Operating System: Windows 10 Home
CPU: AMD Ryzen 5 2600X
GPU: RTX 2070

**Comment by Wieku** [comment]
Fixed by f4d92f7d2a4e49eb493d9d8be759366547096975 on dev branch, keeping open for visibility

**Comment by Wieku** [comment]
Also, thanks a lot by providing video of PLAYED BACK replay from osu!, that helps a lot <3

**Comment by Wieku** [comment]
Should be fixed now
