### ISSUE TITLE
Error When Running danser

### ISSUE THREAD

**Issue by KohakuBeast** [Wieku/danser-go#103]
**Describe the bug**
i try run with cmd and this happen

**Screenshots**
![error](https://user-images.githubusercontent.com/69432003/116614513-37a02d00-a964-11eb-8041-92a0069f4b98.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6401383/danser.log)

**Comment by vladaad** [comment]
You've likely put `\` instead of `\\` in paths in your settings.json, also your danser is out of date.
