### ISSUE TITLE
[Feature Request] Adding the possibility to use Daycore mode instead of halftime

### ISSUE THREAD

**Issue by jaaayoff** [Wieku/danser-go#106]
https://www.youtube.com/watch?v=ib8pVMYG4Mg&ab_channel=Yurio This is what Im talking about. it would be really nice to have this feature !

**Comment by MasterZitron** [comment]
use `-speed` and `-pitch` flags

**Comment by jaaayoff** [comment]
Do I need to use specific value to make it like daycore?

**Comment by MasterZitron** [comment]
I'm pretty sure its 0.5 but I could be mistaken, try things out

**Comment by jaaayoff** [comment]
ok, thx for helping!

**Comment by Wieku** [comment]
Daycore is available with '-mods=DC'
