### ISSUE TITLE
Intro logo don't disappear

### ISSUE THREAD

**Issue by milena-kos** [Wieku/danser-go#113]
**Describe the bug**
Danser's intro logo don't disappear if danser started with -quickstart flag and beatmap don't have intro.

**Screenshots**
![Danser Screenshot 2021 05 05 - 14 04 19 15](https://user-images.githubusercontent.com/75163549/117132055-f74d0e80-adaa-11eb-82fa-e305fa6d6de8.png)
![Danser Screenshot 2021 05 05 - 14 04 26 27](https://user-images.githubusercontent.com/75163549/117132066-fa47ff00-adaa-11eb-8c94-ac823ba21051.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6426618/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel Core i3-4130
GPU: GTX 750 Ti

**Comment by Wieku** [comment]
Does the same happen with `-skip` flag only, right?

**Comment by Wieku** [comment]
Reproduced myself

**Comment by Wieku** [comment]
Should be fixed in dev branch
