### ISSUE TITLE
Compatibility for custom oppais

### ISSUE THREAD

**Issue by MinisBett** [Wieku/danser-go#116]
As far as I have seen you ported oppai to Go. Would it be possible to specify custom oppais for private servers?

**Comment by Wieku** [comment]
Fork danser and port needed changes in app/oppai. I won't add unofficial pp calcs to official repo.

**Comment by Wieku** [comment]
Additional note - if you want to have relax calculated separately from NoMod you need to modify this as well:
https://github.com/Wieku/danser-go/blob/934bb80289befc637c8bc59eeea2d2cc08a0cba3/app/beatmap/difficulty/mods.go#L39
