### ISSUE TITLE
New spinner mover

### ISSUE THREAD

**Issue by robostep9829** [Wieku/danser-go#117]
Maybe curve like that "drawing thing" of hollow gear and solid gear in it with hole inside where you point your pencil i and when you start describing circles it automatically draws like flower with endless petals. I don't know how to accurately describe it, but it should look pretty cool.

Upd.:
Also it looks like nuclear electrons spinning around

**Comment by oofyXD** [comment]
![image](https://user-images.githubusercontent.com/76968752/119716123-a06eae00-be19-11eb-9b7c-6d92b38d0c48.png)
like this?

**Comment by AuracleTech** [comment]
I think he's talking about a Spirograph

**Comment by robostep9829** [comment]
> I think he's talking about a Spirograph
> ![Spirograph Reference](https://camo.githubusercontent.com/fd06dd0914950bf2406abc5d61cdf02d07a574ae724172f2e642b480d487c33b/68747470733a2f2f33647072696e742e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30372f737069726f6772617068322e706e67)

Yesss, this is it!

**Comment by Paladynee** [comment]
triangle spinner algorithm is very similar

**Comment by Wieku** [comment]
Spirograph mover would need an insanely long cursor trail to look good
