### ISSUE TITLE
Speed doesn't work after beatmap ends

### ISSUE THREAD

**Issue by milena-kos** [Wieku/danser-go#121]
**Describe the bug**
When started with `-speed` speed works how expected, but after song ends (if beatmap longer than song) it returns to normal speed.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel Core i3-4130

**Comment by Wieku** [comment]
I've never experienced a ranked map like this. Can you send it?

Putting this at the lowest priority, may fix it at some time.
