### ISSUE TITLE
.json File

### ISSUE THREAD

**Issue by Lefthand666** [Wieku/danser-go#122]
I have no idea what this is:

![Screenshot 2021-05-18 211722](https://user-images.githubusercontent.com/83619381/118742490-81bb5680-b81e-11eb-9520-0fb650aa0940.png)

**Comment by byonicku** [comment]
Check your settings.json you have something that deleted from there or missing ","

**Comment by Lefthand666** [comment]
> Check your settings.json you have something that deleted from there or missing ","

I do? I downloaded the file without tampering with it except for the skin and song file location.

**Comment by byonicku** [comment]
There's character that not intended to be in settings.json
and make sure to change all \ to \\ in your song and skin directory
Example :
![image](https://user-images.githubusercontent.com/82759105/118743129-f1136380-b87b-11eb-960e-7ec1ad1fa7a9.png)

**Comment by Wieku** [comment]
> except for the skin and song file location.

I wonder what could be the problem...

Paths need to have slashes or double backslashes.

**Comment by Lefthand666** [comment]
> There's character that not intended to be in settings.json
> and make sure to change all \ to \\ in your song and skin directory
> Example :
> ![image](https://user-images.githubusercontent.com/82759105/118743129-f1136380-b87b-11eb-960e-7ec1ad1fa7a9.png)

yo it worked! that was so simple lol thanks!

**Comment by Lefthand666** [comment]
> > except for the skin and song file location.
> 
> I wonder what could be the problem...
> 
> Paths need to have slashes or double backslashes.

HI WIEKU
