### ISSUE TITLE
Stuck in the last frame if starting after beatmap ends

### ISSUE THREAD

**Issue by PercyDan54** [Wieku/danser-go#124]
**Describe the bug**
If you use `-start`  beyond the beatmap length it will stuck in the last frame (e.g using `-start 130` with a 2 min beatmap) 

**Expected**
This shouldn't be a thing, ~~but when with recording it will be a infinite loop.~~
Should just throw an error and close

**Comment by Wieku** [comment]
Fixed it in dev branch by capping start flag to start time of the last hitobject
