### ISSUE TITLE
Maximum file size

### ISSUE THREAD

**Issue by MinisBett** [Wieku/danser-go#125]
I think it's difficult to implement as you would need to set a constant bitrate but would it be possible to implement a mode where I can define a file size limit? If I set it to 10mb for example, the output videos of recordings should be 10mb at most and quality should be put down so it fits the file size limit. This would be useful for discord for example, where non-nitro users can only send 8mb files.

**Comment by Wieku** [comment]
Just reencode it yourself.

**Comment by MinisBett** [comment]
The problem is that I would have to play around with the quality every time which sucks when I want to automate the recording. I would do it myself but I have no experience with that recording/encoding stuff.

**Comment by MinisBett** [comment]
This feature would be really good for many users as they may not want big file sizes but don't really know what the best way top reduce it is, especially when you want to share the video on platforms like github

**Comment by vladaad** [comment]
This is already possible by setting a bitrate in encoder options, however I wouldn't recommend it since re-encoding the file via a batch script/handbrake is higher quality (since you can use 2-pass) and you will still have the high quality source file.

**Comment by MinisBett** [comment]
What encoder options should I use so that the quality will always scale so that the resulting file does not exceed a limit?

**Comment by vladaad** [comment]
Impossible, you'll need to change them depending on map length.

**Comment by Wieku** [comment]
> What encoder options should I use so that the quality will always scale so that the resulting file does not exceed a limit?

It's called YouTube, streamable or Discord Nitro

**Comment by MinisBett** [comment]
yeah that's what I'm trying to avoid

**Comment by MinisBett** [comment]
> Impossible, you'll need to change them depending on map length.

So I need to get the estimated total time by adding the epilepsy warning length, result screen length and drain time of the map + 1-3 seconds and then base the kbit per second on that?

**Comment by Wieku** [comment]
Not my problem, create your own script for that. It doesn't need any implementations in danser since people mostly upload them to streamable/YouTube or just have nitro. Clips longer than 20 seconds would look crap anyways.
