### ISSUE TITLE
Does danser run on arm32?

### ISSUE THREAD

**Issue by MinisBett** [Wieku/danser-go#126]
I downloaded the linux release and tried to run it but unfortunately the terminal says that it cannot execute the binary because there is an error in the program file.

This makes me think, that danser does not run on 32-bit systems. Is that true?
Or is the release just made for 64-bit and I need to compile it for 32-bit by myself?

**Comment by Wieku** [comment]
Release is for amd64

Please don't spam issues

**Comment by MinisBett** [comment]
I don't spam issues, I literally just created 2 issues, what's the problem with that? And I would ask you to not just close the issue as I still have questions.
Do I need to compile it by myself or doesn't it run on 32-bit at all?

**Comment by vladaad** [comment]
If your system is ancient enough to be 32-bit chances are the GPU won't support it anyways. And yes you have to compile it yourself.

**Comment by Wieku** [comment]
GitHub issues are not for Q&A, use other media for that.

If your system is 32bit then it means it's most probably too crap for danser

**Comment by MinisBett** [comment]
Well in most repos on github they are commonly used for Q&A so I assumed I could just use them for that too, saw nothing that tells me not to do it. I don't care about the performance, it just needs to run for me

**Comment by MinisBett** [comment]
> If your system is ancient enough to be 32-bit chances are the GPU won't support it anyways. And yes you have to compile it yourself.

You don't necessarily need a GPU to make danser run since CPU encoding is a thing. And I am 99% sure that a RPi is capable to record videos in a decent quality at 60fps within minutes and this is definitely enough for me as quality is not that important in my usecase.

**Comment by MinisBett** [comment]
I tried compiling it and installed many libraries of X11 I need and now I'm stuck with the following error:
```
# github.com/wieku/danser-go/framework/bass
framework/bass/../..//libbass.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by vladaad** [comment]
Compile it yourself then, while CPU encoding is a thing (and default) GPU rendering is the issue here

**Comment by Wieku** [comment]
???
danser still needs gpu. Rendering engine needs OpenGL 4.3 capable graphics card.
It won't work on OpenGLES

**Comment by MinisBett** [comment]
Why doesn't it work with OpenGL ES?

**Comment by Wieku** [comment]
Because it won't. OpenGL ES lacks some features I use.
