### ISSUE TITLE
Osu! runs normal with my GPU but danser doesn't

### ISSUE THREAD

**Issue by tobycm** [Wieku/danser-go#129]
**Describe the bug**
My GPU is integrated into my laptop and it runs osu! well but danser crash immediately when I open it
These are my arguments: "danser -t="Galaxy" -cursors=2"
I have Galaxy Collapse map
This is my settings.json file: https://pastebin.com/f6x3csHD

**Screenshots**

**Logs**
2021/05/24 21:39:24 -------------------------------------------------------------------
2021/05/24 21:39:24 danser-go version: 0.5.2
2021/05/24 21:39:24 Ran using: [danser -t=Galaxy -cursors=2]
2021/05/24 21:39:24 OS:  Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
2021/05/24 21:39:24 CPU: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz, 4 cores
2021/05/24 21:39:24 RAM: 5.9 GiB
2021/05/24 21:39:24 -------------------------------------------------------------------
2021/05/24 21:39:24 Checking GitHub for a new version of danser...
2021/05/24 21:39:24 You're using the newest version of danser.
2021/05/24 21:39:24 DatabaseManager: Initializing database...
2021/05/24 21:39:24 DatabaseManager: Database schema version: 20210423
2021/05/24 21:39:24 DatabaseManager: Database data version: 20210423
2021/05/24 21:39:25 DatabaseManager: Scanning "F:\Computer Program\osu!\Songs" for .osu files...
2021/05/24 21:39:25 DatabaseManager: Scan complete. Found 1185 files.
2021/05/24 21:39:25 DatabaseManager: Comparing files with database...
2021/05/24 21:39:25 DatabaseManager: Compare complete.
2021/05/24 21:39:25 DatabaseManager: Loading beatmaps from database...
2021/05/24 21:39:25 DatabaseManager: Loaded 1125 total.
2021/05/24 21:39:25 Beatmap with exact parameters not found, searching partially...
2021/05/24 21:39:25 Initializing GLFW...
2021/05/24 21:39:26 GLFW initialized!
2021/05/24 21:39:26 panic: Your GPU does not support one or more required OpenGL extensions: [GL_ARB_direct_state_access]. Please update your graphics drivers or upgrade your GPU
2021/05/24 21:39:26 goroutine 1 [running, locked to thread]:
2021/05/24 21:39:26 main.extensionCheck()
2021/05/24 21:39:26 	D:/danser-go/main.go:714 +0x36b
2021/05/24 21:39:26 main.run.func1()
2021/05/24 21:39:26 	D:/danser-go/main.go:402 +0x1acc
2021/05/24 21:39:26 github.com/faiface/mainthread.Call.func1()
2021/05/24 21:39:26 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x36
2021/05/24 21:39:26 github.com/faiface/mainthread.Run(0x7ff7fa9ce448)
2021/05/24 21:39:26 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb7
2021/05/24 21:39:26 main.main()
2021/05/24 21:39:26 	D:/danser-go/main.go:914 +0x165
2021/05/24 21:39:26 
2021/05/24 21:39:26 goroutine 34 [chan receive]:
2021/05/24 21:39:26 github.com/faiface/mainthread.Call(0x7ff7fa9ce440)
2021/05/24 21:39:26 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xca
2021/05/24 21:39:26 main.run()
2021/05/24 21:39:26 	D:/danser-go/main.go:93 +0x34
2021/05/24 21:39:26 github.com/faiface/mainthread.Run.func1(0x7ff7fa9ce448, 0xc0001be000)
2021/05/24 21:39:26 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x2e
2021/05/24 21:39:26 created by github.com/faiface/mainthread.Run
2021/05/24 21:39:26 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xab
2021/05/24 21:39:26 
2021/05/24 21:39:26 goroutine 22 [IO wait]:
2021/05/24 21:39:26 internal/poll.runtime_pollWait(0x23f6e360f08, 0x72, 0x7ff7faa55960)
2021/05/24 21:39:26 	c:/go/src/runtime/netpoll.go:222 +0x65
2021/05/24 21:39:26 internal/poll.(*pollDesc).wait(0xc0000761b8, 0x72, 0x7ff7fa841300, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
2021/05/24 21:39:26 internal/poll.execIO(0xc000076018, 0x7ff7fa9ce320, 0xa6a13cb6f288da01, 0xbd276c39e047a06, 0xa6a13cb6f288dab1)
2021/05/24 21:39:26 	c:/go/src/internal/poll/fd_windows.go:175 +0x113
2021/05/24 21:39:26 internal/poll.(*FD).Read(0xc000076000, 0xc000155000, 0xe03, 0xe03, 0x0, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/internal/poll/fd_windows.go:441 +0x2f6
2021/05/24 21:39:26 net.(*netFD).Read(0xc000076000, 0xc000155000, 0xe03, 0xe03, 0xc000155005, 0xc000091058, 0xc000177828)
2021/05/24 21:39:26 	c:/go/src/net/fd_posix.go:55 +0x56
2021/05/24 21:39:26 net.(*conn).Read(0xc0000da0d8, 0xc000155000, 0xe03, 0xe03, 0x0, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/net/net.go:183 +0x98
2021/05/24 21:39:26 crypto/tls.(*atLeastReader).Read(0xc00009daa0, 0xc000155000, 0xe03, 0xe03, 0x0, 0xc000040800, 0x0)
2021/05/24 21:39:26 	c:/go/src/crypto/tls/conn.go:776 +0x6a
2021/05/24 21:39:26 bytes.(*Buffer).ReadFrom(0xc00013e5f8, 0x7ff7faa546c0, 0xc00009daa0, 0x7ff7fa21d2ec, 0x7ff7fa91aba0, 0x7ff7fa981920)
2021/05/24 21:39:26 	c:/go/src/bytes/buffer.go:204 +0xbe
2021/05/24 21:39:26 crypto/tls.(*Conn).readFromUntil(0xc00013e380, 0x23f6e26e158, 0xc0000da0d8, 0x5, 0xc0000da0d8, 0x7ff7fa938ce0)
2021/05/24 21:39:26 	c:/go/src/crypto/tls/conn.go:798 +0xf3
2021/05/24 21:39:26 crypto/tls.(*Conn).readRecordOrCCS(0xc00013e380, 0x0, 0x0, 0xc0000da0d0)
2021/05/24 21:39:26 	c:/go/src/crypto/tls/conn.go:605 +0x12d
2021/05/24 21:39:26 crypto/tls.(*Conn).readRecord(...)
2021/05/24 21:39:26 	c:/go/src/crypto/tls/conn.go:573
2021/05/24 21:39:26 crypto/tls.(*Conn).Read(0xc00013e380, 0xc000171000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/crypto/tls/conn.go:1276 +0x173
2021/05/24 21:39:26 bufio.(*Reader).Read(0xc00016c960, 0xc00015e578, 0x9, 0x9, 0x7ff7fa661f6b, 0xc000177c78, 0x7ff7fa2189eb)
2021/05/24 21:39:26 	c:/go/src/bufio/bufio.go:227 +0x238
2021/05/24 21:39:26 io.ReadAtLeast(0x7ff7faa545a0, 0xc00016c960, 0xc00015e578, 0x9, 0x9, 0x9, 0xc00008bb30, 0x6660c62a434000, 0xc00008bb30)
2021/05/24 21:39:26 	c:/go/src/io/io.go:328 +0x8e
2021/05/24 21:39:26 io.ReadFull(...)
2021/05/24 21:39:26 	c:/go/src/io/io.go:347
2021/05/24 21:39:26 net/http.http2readFrameHeader(0xc00015e578, 0x9, 0x9, 0x7ff7faa545a0, 0xc00016c960, 0x0, 0x7ff700000000, 0xc00016a780, 0x0)
2021/05/24 21:39:26 	c:/go/src/net/http/h2_bundle.go:1477 +0x8e
2021/05/24 21:39:26 net/http.(*http2Framer).ReadFrame(0xc00015e540, 0xc00016a780, 0x0, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/net/http/h2_bundle.go:1735 +0xa8
2021/05/24 21:39:26 net/http.(*http2clientConnReadLoop).run(0xc000177fa8, 0x0, 0x0)
2021/05/24 21:39:26 	c:/go/src/net/http/h2_bundle.go:8322 +0xe7
2021/05/24 21:39:26 net/http.(*http2ClientConn).readLoop(0xc000084a80)
2021/05/24 21:39:26 	c:/go/src/net/http/h2_bundle.go:8244 +0x76
2021/05/24 21:39:26 created by net/http.(*http2Transport).newClientConn
2021/05/24 21:39:26 	c:/go/src/net/http/h2_bundle.go:7208 +0x6c5
2021/05/24 21:39:26 

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i3-4005U ~ 1.70GHz
GPU: Intel HD Graphics Family

**Comment by vladaad** [comment]
Your GPU does not support one or more required OpenGL extensions.

**Comment by Wieku** [comment]
I don't know what osu! has to danser in terms of launchability.
