### ISSUE TITLE
(not a issue) I want to ask about something.

### ISSUE THREAD

**Issue by BULL3TB0T** [Wieku/danser-go#130]
How can I include danser in a knockout? I don't know how to do that, can someone help me?

**Comment by M3IY0U** [comment]
I know the invite link isn't that obvious in the readme, but please try asking that question (or similar ones) in the helpdesk channel on the [discord server](https://discord.gg/UTPvbe8), we'll be able to help you much better there.

**Comment by BULL3TB0T** [comment]
Thank you, thank you. I was going to find a discord link but nothing lol.
