### ISSUE TITLE
Not finding beatmaps in sub-folders

### ISSUE THREAD

**Issue by Respektive** [Wieku/danser-go#131]
I have my beatmaps organized by ranked year and danser is unable to find any of the maps located in the sub-folders, it's only finding maps directly in the songs folder.

![image](https://user-images.githubusercontent.com/22381687/119937840-50d6d200-bf40-11eb-9acf-8063a63b6d1d.png)
![image](https://user-images.githubusercontent.com/22381687/119937913-6946ec80-bf40-11eb-9282-6741ececf756.png)

**Comment by sbrstrkkdwmdr** [comment]
yeah that's how it's coded. just change song directory in settings.json or move the mapset folder

**Comment by Wieku** [comment]
It's intentional
