### ISSUE TITLE
Why does knockout mode not work?

### ISSUE THREAD

**Issue by brickyosu** [Wieku/danser-go#133]
There are no other cursors and no players.
**Screenshots**
![danser 0 5 2 - NOMA - Brain Power  INFINITE  6_4_2021 7_52_40 PM](https://user-images.githubusercontent.com/85379324/120878026-9b72d280-c56e-11eb-9c24-aaf94773871f.png)

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by sbrstrkkdwmdr** [comment]
you have to download replays and drag them into the danser\replays\ folder. -knockout without replays just turns on game interface

**Comment by saieeshb** [comment]
You need to have a replays folder with replays in it. then use the -knockout flag. If you don't have a replays folder, make one named replays inside the danser folder.

**Comment by brickyosu** [comment]
i have replays folder but it still not work :(

**Comment by brickyosu** [comment]
OHHHH i get it i looked at tutorial
