### ISSUE TITLE
how to get 50 replays on osu beatmap

### ISSUE THREAD

**Issue by brickyosu** [Wieku/danser-go#134]
how do i put 50 cursors in knockout mode and danser appearing at the end?
**Screenshots**

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by Wieku** [comment]
It's only possible for me.

**Comment by Wieku** [comment]
Also please fill issue template properly.

**Comment by brickyosu** [comment]
why

**Comment by brickyosu** [comment]
why cant we do it

**Comment by AuracleTech** [comment]
> why cant we do it

Tbh I find it pretty simple, so people without knowledge or experience makes video on YouTube
This allowed people with programming skills to make quality videos
