### ISSUE TITLE
Reverse arrow not visible

### ISSUE THREAD

**Issue by AuracleTech** [Wieku/danser-go#138]
**Description**
No reverse arrow

**Screenshots & Videos**
Here's the in game look
![In game](https://osu.ppy.sh/ss/16711334/61e5)
Here's how it looks on danser [clip](https://user-images.githubusercontent.com/40531871/121791639-22046100-cbba-11eb-9582-4ef1de3ac24d.mp4)

Here's the arrow I use, I noticed I only have @2x because my skin is HD only, this may be it
![reversearrow@2x](https://user-images.githubusercontent.com/40531871/121791707-b8388700-cbba-11eb-9f06-1a7833ca92f1.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6643055/danser.log)

**Computer configuration**
Operating System: Windows 10
CPU: Ryzen 7 2700
GPU: GTX650

Also can you unban Auracle#1001 from your discord, would be easier to communicate thanks

**Comment by Wieku** [comment]
If you have endcircles turned off in settings then reverse arrows won't show up
