### ISSUE TITLE
when i type in the beatmap and difficulty it says beatmap not found when i have it

### ISSUE THREAD

**Issue by proisyou12345** [Wieku/danser-go#139]
it says beatmap not found when i type in the commands to start it i type the title and difficulty but it says beatmap not found i tried a couple of more times but it didnt work 

![image](https://user-images.githubusercontent.com/85957377/122094522-8f0f3500-ce0c-11eb-9010-ef4ec36f0e9b.png)
2021/06/15 19:01:20 Checking GitHub for a new version of danser...
2021/06/15 19:01:21 You're using the newest version of danser.
2021/06/15 19:01:21 DatabaseManager: Initializing database...
2021/06/15 19:01:21 DatabaseManager: Database schema version: 20210423
2021/06/15 19:01:21 DatabaseManager: Database data version: 20210423
2021/06/15 19:01:21 DatabaseManager: Scanning "C:\Users\buszt\AppData\Local\osu!\Songs" for .osu files...
2021/06/15 19:01:21 DatabaseManager: Scan complete. Found 648 files.
2021/06/15 19:01:21 DatabaseManager: Comparing files with database...
2021/06/15 19:01:21 DatabaseManager: Compare complete.
2021/06/15 19:01:21 DatabaseManager: Loading beatmaps from database...
2021/06/15 19:01:21 DatabaseManager: Loaded 568 total.
2021/06/15 19:01:21 Beatmap with exact parameters not found, searching partially...
2021/06/15 19:01:21 Beatmap not found, closing...

**Computer configuration:**
Operating System: Windows 10
CPU: Intel core i5
GPU: GTX1050

**Comment by Wieku** [comment]
I advice starting a "reading comprehension" course.
