### ISSUE TITLE
Hi, i would like some help with the rainbow cursor

### ISSUE THREAD

**Issue by CillClick** [Wieku/danser-go#141]
When i try to use the rainbow cursor in a custom skin, its just red, but when i use the default (danser) skin, it does work. And it works just fine with the hitcircles. Can someone please explain why this happens and how i can fix it?

Oh btw heres a [Screenshot](https://imgur.com/a/8nuJFNw) if you want it

**Comment by Wieku** [comment]
Cursor colors are not being applied when skin's cursor is used

**Comment by CillClick** [comment]
Im sorry, can you explain? im very dumb so i dont know how to apply that-
And sorry for the late reply-

**Comment by CillClick** [comment]
Oh, well can i change the danser cursor?

**Comment by byonicku** [comment]
Please ask about this stuff in danser discord.

This meant for issues like bug and glitches not how to use the app

**Comment by CillClick** [comment]
Oh, sorry. Well now i know, thanks!
