### ISSUE TITLE
background video is distorted

### ISSUE THREAD

**Issue by timofey260** [Wieku/danser-go#143]
**Describe the bug**
i play danser width background video, and it is distorted after run

**Screenshots**
![изображение_2021-06-22_200009](https://user-images.githubusercontent.com/69044246/122968657-72d34100-d394-11eb-90d3-d9ebb0a84e81.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6696062/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 7500U
GPU: intel HD graphics 620

**Comment by Def0lttGit** [comment]
Why do you have an osu! cursor dance cheat on your desktop? (just wondering)

**Comment by timofey260** [comment]
I wanted to look at a beautiful cursor dance (but it doesn`t work)
@Def0lttGit

**Comment by Wieku** [comment]
Fixed in dev branch. Keeping open for visibility
