### ISSUE TITLE
be able to change where danser read and find osu! stuffs

### ISSUE THREAD

**Issue by NeekoVN** [Wieku/danser-go#152]
**Describe the bug**
so i installed osu! in another drive because my hdd is so damn slow
and danser just read the default osu! install folder with no way to change that

**Screenshots**
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand

**Logs**

**Computer configuration:**
Operating System: Windows 11 + macOS Catalina
CPU: Intel i5 3210M
GPU: intel HD 4000
Sound Card: idk

**Comment by sbrstrkkdwmdr** [comment]
settings.json

**Comment by NeekoVN** [comment]
oh
sorry

**Comment by Wieku** [comment]
github is not a place for jokes, please.
