### ISSUE TITLE
Background video option doesnt work

### ISSUE THREAD

**Issue by danielkp1234** [Wieku/danser-go#154]
Hello, so I have this in settings trying to get a background video to play during the map but it doesn't work
![image](https://user-images.githubusercontent.com/19412591/124771463-6d046080-df3b-11eb-990b-b0af24392d7b.png)

I have tried both the newest build and built the dev branch myself. I have also tried multiple songs but i cant the get background video to load.

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6777724/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5-1035G1
GPU: Intel UHD Graphics

**Comment by Wieku** [comment]
Ehh

**Comment by vladaad** [comment]
You need to install FFmpeg to playback background video

**Comment by Wieku** [comment]
Stop burning issue numbers please.

**Comment by Wieku** [comment]
So you can build it but can't read the line in logs that says that ffmpeg failed to start. Hmm...
