### ISSUE TITLE
Hiding danser's +AT in knockout

### ISSUE THREAD

**Issue by NOOB1KXGOD** [Wieku/danser-go#155]
I tried many aliases of auto mod but none of them hide it for danser. is this supposed to work like so or i should hide it another way?

https://imgur.com/a/wUp1mHr

**Comment by Wieku** [comment]
It's intended to be like that.

**Comment by NOOB1KXGOD** [comment]
then how did you hide it?

![image](https://user-images.githubusercontent.com/69494286/125110795-80135e00-e0fe-11eb-8da5-9f9b5e49c2a4.png)

**Comment by Wieku** [comment]
I pretend I hasn't seen that question because it's a bit obvious.
