### ISSUE TITLE
[Suggestion] Allow Alpha Channel being outputted when using "-record" argument and H265 codec

### ISSUE THREAD

**Issue by nucularr** [Wieku/danser-go#156]
Title says it, I think an option to completely remove the background and instead render objects on transparency would be great for editing purposes. Would replace currently use "green screen background" method for a more clean and sophisticated render, without chroma keying artifacts for post-editing results

**Comment by Wieku** [comment]
But why, I don't see any purpose for it tbh.

**Comment by Wieku** [comment]
Also ffmpeg doesn't support alpha for HEVC, so I'm closing that ticket.

**Comment by FibreTTP** [comment]
Consider re-opening. Being able to manipulate the UI elements outside of danser would allow for more flexibility, and will save time having to re-render. FFmpeg has also had support for alpha/transparency in HEVC for a while now (plus the other codecs available with ffmpeg).
