### ISSUE TITLE
Being able to edit the wiki

### ISSUE THREAD

**Issue by byzocker** [Wieku/danser-go#158]
**Describe the bug**
You can edit here and i don't think you're supposed to be able to 

https://github.com/Wieku/danser-go/wiki/Knockout-Guide

**Computer configuration:**
Operating System: Windows 10 20H2
CPU: Intel i5 7400
GPU: GTX1050 Mini

**Comment by TechnoJo4** [comment]
> i don't think you're supposed to be able to
please read about what a wiki is lmao

**Comment by vladaad** [comment]
You're welcome to contribute!

**Comment by Wieku** [comment]
That's how wiki works. I could restrict it to collaborators but for what use. If someone wants to fix a mistake they don't need to ask me for permission. And as with wikis, I can easily revert any vandalism (which you did) and ban them from danser.
