### ISSUE TITLE
What terminal to use

### ISSUE THREAD

**Issue by EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE1** [Wieku/danser-go#160]
I want to use this, but I cannot do anything with it because I tried using the only terminals/command prompts I know (Windows command prompt and VSC terminal) but neither of them worked, please tell me what command prompt/terminal to use or tell me a command to run with dancer to use it

**Comment by byonicku** [comment]
Powershell / CMD works fine if you launch it from danser directory, and please check the Wiki to setup it.

**Comment by TechnoJo4** [comment]
they should work, *you* fucked up. github issues is not for troubleshooting, join the discord server.
