### ISSUE TITLE
skins without hitcircleoverlay not using default skin hitcircle overlay (like idke skin)

### ISSUE THREAD

**Issue by sbrstrkkdwmdr** [Wieku/danser-go#161]
![sdhfgfdgdg](https://user-images.githubusercontent.com/71379681/126623061-d220ec7d-c775-4d9d-affc-4d4eab7f2f36.png)

**Comment by abstrakt-osu** [comment]
The hitcircle overlay in idke's skin has the filename `hitcircleoverlay2x.png` without the `@` character. It's funny cause I also happened to notice this while testing with the idke+1.2 skin.

**Comment by Wieku** [comment]
@abstrakt-osu That's not true at all.
