### ISSUE TITLE
Hitsound

### ISSUE THREAD

**Issue by xeolyon471** [Wieku/danser-go#162]
The hyperpigeon [HP] hitsound and other similar skin like aricin skin doesn't sound what it suppose to.

**Comment by Wieku** [comment]
Maybe turn off beatmap hitsounds first...

**Comment by xeolyon471** [comment]
![image](https://user-images.githubusercontent.com/88121164/127453331-1f8a5988-442f-4d39-bd40-e7417b2cca83.png)
humm but it still doesn't seem to be working even tho I already update to the latest version.

**Comment by sbrstrkkdwmdr** [comment]
that's osr2mp4 not danser...

**Comment by xeolyon471** [comment]
oh sorry I thought it's the same

**Comment by Wieku** [comment]
Bitch what

**Comment by xeolyon471** [comment]
well thanks for letting me know.  I apologize ╯︿╰
