### ISSUE TITLE
missing "Dance" wiki entry

### ISSUE THREAD

**Issue by h3oCharles** [Wieku/danser-go#164]
**Describe the bug**

Dance wiki entry is missing

**Screenshots**
![image](https://user-images.githubusercontent.com/8020330/127741019-e3e1be5b-5ef2-4985-9a40-66470ba0fcc4.png)

**Logs**
Put danser.log here.
not applicable

**Computer configuration:**
not applicable

**Comment by vladaad** [comment]
it's not finished yet - if you want to, you can make the page in a similar style to other pages (it IS a wiki after all)

**Comment by h3oCharles** [comment]
i could've sworn i've seen that entry, like, yesterday (relative to the time of writing this)
