### ISSUE TITLE
panic: Failed to parse settings.json! Please re-check the file for mistakes. Error: invalid character 'o' in string escape code

### ISSUE THREAD

**Issue by h3oCharles** [Wieku/danser-go#165]
**Describe the bug**
despite correctly writing the cmd arguments, danser fails to load
idk if this is a user error or not

**Screenshots**
not applicable

**Logs**
Put danser.log here.
https://pastebin.com/jbYmXacc

here's settings.json as well https://pastebin.com/kmiZun9H
there shouldn't be much worth mentioning, I only changed songs and skins dirs to make sure I don't get a map not found error

the bat file contains:
`start danser.exe -artist="Kawai Sprite" -title="Ugh" difficulty="TAG 2" -tag=2`

map in question is https://osu.ppy.sh/beatmapsets/1514399#osu/3100560

**Computer configuration:**
Operating System: Microsoft Windows 10 Pro 10.0.19042 Build 19042
CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz, 4 cores
GPU: GTX 1050
Sound Card: not applicable...?

**Comment by Wieku** [comment]
How is that an issue wtf... Please follow wiki.

**Comment by h3oCharles** [comment]
user error indeed, sorry
