### ISSUE TITLE
new idea about Knockout

### ISSUE THREAD

**Issue by SS-YG** [Wieku/danser-go#169]
Could you add "Full Combo Mode" ro something to danser?
In some maps, danser cannot click the circles quickly and accurateky, so that the score is 100, 50 or 0,
This mode is makes the circle be hit automatically, Instead of having the cursor automatically move to the circle and hit it.

**Comment by sbrstrkkdwmdr** [comment]
danser always FCs except on 2B maps

**Comment by SS-YG** [comment]
But I hope it can FC on any map.
