### ISSUE TITLE
danser's sound problem

### ISSUE THREAD

**Issue by SS-YG** [Wieku/danser-go#171]
When a lot of circles play hit sounds at the same time,

the sound will have a heavy bass,

and the sound of other frequency bands will become smaller.

**Comment by byonicku** [comment]
On what map?

**Comment by Wieku** [comment]
Just don't play a lot of hitsounds at the same time. Danser is not made for spam maps like The Empress

**Comment by Wieku** [comment]
Also in recording mode don't raise volume above 50%
