### ISSUE TITLE
Using danser-go, and i'm seeing some issues 

### ISSUE THREAD

**Issue by Kanteer** [Wieku/danser-go#172]
**Describe the bug**
When running the "go build"  command, some issues show up and I wanna know if this is normal.
I'm not that good with command prompt and stuff so I just wanna know if this is normal.

**Logs**
github.com/wieku/danser-go/framework/platform
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%
github.com/wieku/danser-go/framework/qpc
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%
github.com/go-gl/glfw/v3.3/glfw
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%
github.com/mattn/go-sqlite3
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%
github.com/go-gl/gl/v3.3-core/gl
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%

**Comment by Wieku** [comment]
Maybe follow README.md properly first?
