### ISSUE TITLE
Knockout Mode 3 HR Score Text Isn't reversed

### ISSUE THREAD

**Issue by Paladynee** [Wieku/danser-go#174]
**Describe the bug**
When using HR in a Knockout with knockout mode 3, when you hit a 100, a 50 or miss while clicking a slider, the relevant text appears at inverted (HR slider position) place. Instead of the non-inverted (non-HR) place like other replays which don't use HR.

**Video Proof**
https://youtu.be/oEWXW_KVzL8
This video both includes making of the replay, and the danser view.

**Computer configuration:**
Operating System: Windows 10 64-bit
CPU: Intel i3 10100F
GPU: GTX 1050 Ti

**Comment by ynot01** [comment]
Had this happen in 0.11.0 (Mar 2025 release)
