### ISSUE TITLE
Can you add auto mode for Danser to display in the upper right corner? Like the original OSU.

### ISSUE THREAD

**Issue by SS-YG** [Wieku/danser-go#177]
Can you add auto mode for Danser to display in the upper right corner?
Like the original OSU.

**Comment by sbrstrkkdwmdr** [comment]
-mods=AT

**Comment by ThomasCatlow** [comment]
If you're going to ask questions like this, please join the Discord server and ask in the #helpdesk channel, don't burn issue numbers.

**Comment by Wieku** [comment]
Please stop spamming issues and use discord.

Next question issue => ban

**Comment by SS-YG** [comment]
Sorry, I don't know discord number

**Comment by Wieku** [comment]
...
