### ISSUE TITLE
Danser's video will play much faster than the original OSU.

### ISSUE THREAD

**Issue by SS-YG** [Wieku/danser-go#178]
Danser's video will play much faster than the original OSU.
As a result, the map cannot match the video background perfectly.

I need to modify the video start time of the MAP file by myself,

[After measurement and practice, the start time of video is 1800 milliseconds faster.]

**Comment by SS-YG** [comment]
Maybe there's something wrong with this problem. is the video starts playing time faster than the original.

**Comment by Wieku** [comment]
I undestood nothing. Also no examples, logs, anything. Closing.
