### ISSUE TITLE
Support of .osr replay playback

### ISSUE THREAD

**Issue by fr3fou** [Wieku/danser-go#18]

**Comment by Wieku** [comment]
Do you mean saving danser play to .osr file or opening a .osr file?

**Comment by fr3fou** [comment]
Opening an .osr file

**Comment by Wieku** [comment]
Partial support was introduced in 0.4.0b, although mods are not supported fully yet.

**Comment by dundeez** [comment]
Any way to export as an osr file?

**Comment by Wieku** [comment]
> Any way to export as an osr file?

No, recording to mp4 directly in danser is in progress.

**Comment by dundeez** [comment]
> > Any way to export as an osr file?
> 
> No, recording to mp4 directly in danser is in progress.

That's even better, thanks.

**Comment by Ning1253** [comment]
Hello, I was looking at this (looks AMAZING btw) and I was wondering what the command line option actually is to view a replay?

**Comment by Ning1253** [comment]
Ok so I figured it out - however the replay played slightly differently than in game, slider breaking a few times where there hadn't been a slider break... should I add this as a separate issue?
