### ISSUE TITLE
panic: runtime error: index out of range [3] with length 2

### ISSUE THREAD

**Issue by Bojosu** [Wieku/danser-go#186]
When running the `./danser -id 0` command I get the error: `panic: runtime error: index out of range [3] with length 2`.
It only happens after the programm is already done with finding new beatmaps and through some of the importing process.
It also seems to always be happening at the beatmap ID `139xxx` - the problem occured on `1396777` and `1397392` (when running the programm twice without changing anything)
Ive been using a Symlink to change my Songs folders directory to a different Disk, though I also changed the directory in the `.json` file, so my Osu folder is in `C:` but my Songs folder in `D:` (when keeping the Songs directory to `C:\Users\AppData\Local\osu!\Songs` running `./danser -id 0`) doesnt work at all

Screenshot of my Error logs since they arent shown in the log
![Error logs](https://user-images.githubusercontent.com/73035009/131828551-b66bd209-0b5d-4d09-9cd6-54bd7d5bb19b.png)

https://pastebin.com/bPTM3DRg -> pastebin of the `.json` file
[danser.log](https://github.com/Wieku/danser-go/files/7098206/danser.log)

Operating System: Windows 10
CPU: AMD Ryzen 5 2600X
GPU: GTX1070

**Comment by Wieku** [comment]
Don't use `-id 0` because that id is assigned to non-published and old maps (I think osu! takes ID from API).
But it would be nice to have .osu files of those maps

**Comment by Bojosu** [comment]
Your Theory of Corrupt beatmaps being the issue is probably correct, after deleting the maps out of the actual osu! folder (apparently deleting them ingame still keeps them in the Songs folder) and redownloading them the importing works fine,


The Database is still loading 3000 less maps than what I have but the programm is working perfect otherwise (maybe that comes from only using `-md5 0` and not `-id 0` aswell?)
![image](https://user-images.githubusercontent.com/73035009/131888382-ebf014e8-3cf4-4f2b-a325-d164848a2a73.png)
![image](https://user-images.githubusercontent.com/73035009/131887618-197c3c6f-d765-47e9-94f1-e276b2ca0070.png)

Thanks for you help!

**Comment by Wieku** [comment]
Those 3000 maps are probably maps from other game modes.
