### ISSUE TITLE
cant run danser

### ISSUE THREAD

**Issue by zxcdevlop** [Wieku/danser-go#192]
i tried to run danser using the command prompt (daner <arguments>) and it only says "The syntax of the command is incorrect." anyone know a fix?

**Comment by sbrstrkkdwmdr** [comment]
it's danser not daner

**Comment by h3oCharles** [comment]
what command are you using?

**Comment by zxcdevlop** [comment]
the danser <arguments> command

**Comment by zxcdevlop** [comment]
danser <arguments>

**Comment by zxcdevlop** [comment]
danser arguments

**Comment by zxcdevlop** [comment]
that one

**Comment by h3oCharles** [comment]
"danser argument" is what's inside the bat file? that won't work, you need to replace "arguments" with actual arguments, that are listed in the readme

**Comment by Wieku** [comment]
Is that a troll?
