### ISSUE TITLE
Access Denied error

### ISSUE THREAD

**Issue by ehalcyon** [Wieku/danser-go#193]
No idea what happened, but I was given an "Access Denied" error when I tried running danser. The application even showed that it is 0 Bytes

**Screenshot**
![Screenshot 2021-09-16 100519](https://user-images.githubusercontent.com/90811263/133537474-7d0d617f-1d92-412f-a6b2-bce3106ffd15.jpg)

**Computer configuration:**
Operating System: Windows 10 Pro
CPU: Processor	Intel Core i5-7300U

**Comment by sbrstrkkdwmdr** [comment]
redownload and try again

**Comment by ehalcyon** [comment]
> redownload and try again

that fixed the issue. thanks!
