### ISSUE TITLE
missing generated .json file

### ISSUE THREAD

**Issue by i-yitsure** [Wieku/danser-go#194]
I write the command correctly but for some reason this same program (powershell) after of load all beatmapsets didn't generated the .json file
Edit: i tried generate 2 or 3 time if the log is more longer than normal

**Screenshot:**
![image](https://user-images.githubusercontent.com/28587232/133733172-b1b6625d-83c8-4c7e-81f7-9f7900025c5e.png)

**Danser log:**
[danser.log](https://github.com/Wieku/danser-go/files/7183059/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: AMD A8-7410 APU

**Comment by vladaad** [comment]
It's in the settings folder

**Comment by i-yitsure** [comment]
thanks, i forgot that the adobe Dreamwaver CC change the form for indentify the file, my err :P
