### ISSUE TITLE
Hitcircle texture appears on very-fast ending sliders' ends

### ISSUE THREAD

**Issue by Paladynee** [Wieku/danser-go#195]
**Describe the bug**
Hitcircle texture appears at the end of sliders on near-instant ending sliders. (See video below 0:30 timestamp)

**Screenshots**
https://www.youtube.com/watch?v=JxtzOXrIlv0

**Computer configuration:**
OS: Windows 10 x64
CPU: i3 10100F
GPU: GTX 1050 Ti

**Comment by Paladynee** [comment]
danser version latest stable i guess? (says up to date on danser run)

**Comment by Wieku** [comment]
That's not a bug.

**Comment by Paladynee** [comment]
wait what do you mean so its intended?

**Comment by Wieku** [comment]
Look how snake out works for slower sliders. That's intended behavior.

**Comment by Paladynee** [comment]
> Look how snake out works for slower sliders. That's intended behavior.

so the hitcircle texture follows the sliderfollow texture before disappearing when snake out is enabled?

**Comment by Wieku** [comment]
Yes.

**Comment by Paladynee** [comment]
aight man when i couldnt see the same thing in osu itself i thought it was a bug.

**Comment by Wieku** [comment]
I planned to add an option to make heads/tails static to next release anyways so stay tuned ;)
