### ISSUE TITLE
[Proposal] offset as run argument

### ISSUE THREAD

**Issue by AuracleTech** [Wieku/danser-go#199]
Currently Offset is in the config
It could be much valuable if we had an offset setting as run argument 😁👍

**Comment by Wieku** [comment]
If offset have to be changed with each run then I would seriously look at your audio setup in your place.

**Comment by AuracleTech** [comment]
I would be easier to use an on unranked maps.
Unranked maps are known to have bad offset, with a 280hz monitor, a high end PC and -1 offset on almost all ranked maps I can tell you my offset is okay.

But you do you I guess.

**Comment by Wieku** [comment]
I think instead of `-offset` argument, shouldn't per map offset be better? Changeable by (shift for higher precision) and -/+ (I would move cursors to [/] then)

**Comment by AuracleTech** [comment]
I'm not sure to understand but I think you're referring to starting danser and playing in it, but I'm speaking about making replays.
-offset could be used in a GUI and/or in a custom batch file
But yes for people who play in danser to make replays could use offset in game too with shift -+

**Comment by Wieku** [comment]
Can be tested in `dev` branch. Although keep in mind it works inverted compared to osu!'s local offset
