### ISSUE TITLE
done correctly, but instantly exits

### ISSUE THREAD

**Issue by KoolKidz112** [Wieku/danser-go#20]
I entered everything correctly, but when it actually starts, it goes fullscreen and then exits shortly after. Is there a fix to this or is there none since this is abandoned?

**Comment by Wieku** [comment]
Maybe give me the logs? I don't have the crystal ball, you know

**Comment by KoolKidz112** [comment]
2019/07/20 20:11:42 Database version:  20181111
2019/07/20 20:11:42 Checking database...
2019/07/20 20:11:42 Imported 0 new beatmaps.
2019/07/20 20:11:42 Found 36 cached beatmaps. Loading...
2019/07/20 20:11:42 Loaded 36 total.
2019/07/20 20:11:43 Loading texture:  assets/textures/dansercoin.png
2019/07/20 20:11:43 Loading texture:  assets/textures/dansercoin48.png
2019/07/20 20:11:43 Loading texture:  assets/textures/dansercoin24.png
2019/07/20 20:11:43 Loading texture:  assets/textures/dansercoin16.png
2019/07/20 20:11:43 GLFW initialized!
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowTexStorage3D(0x0, 0x400008c1a, 0x100
000008058, 0x100001000)
        _cgo_gotypes.go:18942 +0x4c
github.com/go-gl/gl/v3.3-core/gl.TexStorage3D(0x400008c1a, 0x100000008058, 0x100
001000)
        C:/Users/Wieku/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:12103
+0x64
github.com/wieku/danser/render/texture.newStore(0x1, 0x1000, 0x1000, 0x4, 0xc000
084268)
        C:/Users/Wieku/go/src/github.com/wieku/danser/render/texture/texture.go:
58 +0xd1
github.com/wieku/danser/render/texture.NewTextureAtlas(0x1000, 0x4, 0x60)
        C:/Users/Wieku/go/src/github.com/wieku/danser/render/texture/atlas.go:40
 +0x18a
github.com/wieku/danser/render/font.LoadFont(0xa4cd40, 0xc0000740b8, 0xc0000740b
8)
        C:/Users/Wieku/go/src/github.com/wieku/danser/render/font/font.go:61 +0x
171
main.run.func1()
        C:/Users/Wieku/go/src/github.com/wieku/danser/main.go:163 +0xfaf
github.com/faiface/mainthread.Call.func1()
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:63 +0x
36
github.com/faiface/mainthread.Run(0x9fa988)
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:44 +0x
c4
main.main()
        C:/Users/Wieku/go/src/github.com/wieku/danser/main.go:257 +0x4f

goroutine 19 [chan receive]:
github.com/faiface/mainthread.Call(0xc000004060)
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:66 +0x
c9
main.run()
        C:/Users/Wieku/go/src/github.com/wieku/danser/main.go:36 +0xa3
github.com/faiface/mainthread.Run.func1(0x9fa988, 0xc00003e120)
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:37 +0x
2e
created by github.com/faiface/mainthread.Run
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:36 +0x
b8

goroutine 4 [select]:
database/sql.(*DB).connectionOpener(0xc0001ea000, 0xa52360, 0xc0000346c0)
        C:/Go/src/database/sql/sql.go:1001 +0xef
created by database/sql.OpenDB
        C:/Go/src/database/sql/sql.go:671 +0x164

goroutine 5 [select]:
database/sql.(*DB).connectionResetter(0xc0001ea000, 0xa52360, 0xc0000346c0)
        C:/Go/src/database/sql/sql.go:1014 +0x102
created by database/sql.OpenDB
        C:/Go/src/database/sql/sql.go:672 +0x19a
rax     0xc000065450
rbx     0xc000065450
rcx     0x8c1a
rdi     0xc000065450
rsi     0xd2c240
rbp     0xc000065408
rsp     0x22fd48
r8      0x8058
r9      0x1000
r10     0x7feadb00000
r11     0x659cc40
r12     0xffffffffffffffff
r13     0x2
r14     0x1
r15     0x100
rip     0x0
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by Wieku** [comment]
Your graphics card is too old.

**Comment by KoolKidz112** [comment]
Ok thanks!
