### ISSUE TITLE
[Feature] Decouple settings, database, assets, etc. from binary directory

### ISSUE THREAD

**Issue by keksbg** [Wieku/danser-go#203]
This is mostly a proposal that would apply to packages on Linux/BSD, preferably as just a regular build flag.
## Goals
- Decouple the different directories/files from the binary: this would result in an easier time packaging danser for different Linux (or BSD) distributions as it would no longer require direct patching to the source code to modify the location, or to install everything in a place like `/opt`.
- Provide flags or settings to modify *where* those decoupled directories/files would be installed: this results in easier installation across different distributions as package maintainers can decide which would be the best location for their own distribution.
- Additionally, check the `.settings` directory in the home directory of the user executing the binary for configuration files, database files, etc. to not require it all to be located in a global location and be more easily usable by multiple users on the same machine.

**Comment by Wieku** [comment]
Resolved in 0.6.8:

* danser needed libs (libbass, libyuv, assets.dpak) are in `/usr/lib/danser` if executable is located in `/usr/bin/danser` or `/usr/lib/danser/danser`
* configuration files are in `~/.config/danser` or `$XDG_CONFIG_HOME/danser`
* data files (danser.db, logs, screenshots, videos, Songs/Skins when relative paths in json are used) are in `~/.local/share/danser` or `$XDG_DATA_HOME/danser`
