### ISSUE TITLE
beatmap search by id

### ISSUE THREAD

**Issue by MelonIs45** [Wieku/danser-go#21]
I guess this is an enhancement but would it be possible to add a search filter by beatmap id, such as id=123456 instead of having to type out the name of the beatmap as well as the difficulty etc. I've never used github before so sorry if this is in the wrong section.

**Comment by Wieku** [comment]
You're in good section. Thank you, never thought about searching in that way.

**Comment by LayneTheEpic** [comment]
That would actually be really handy ^^
