### ISSUE TITLE
Stream wobble cannot disable with "false" argument

### ISSUE THREAD

**Issue by qwertyuiothyyt** [Wieku/danser-go#213]
**Describe the bug**
When I want to disable stream wobble I changed the true value to false, which did not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/52452452/140756895-26f51d30-f704-49c3-8b0d-7ec1276ccd1f.png)

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5 4440
GPU: GT1030 (if it's a graphics issue)
Sound Card: not important (if it's a sound issue)

**Comment by qwertyuiothyyt** [comment]
*also i used the spline mover

**Comment by Wieku** [comment]
You have StreamHalfCircle enabled which overrides StreamWobble setting.
