### ISSUE TITLE
How do I export?

### ISSUE THREAD

**Issue by Liam1006** [Wieku/danser-go#217]
When I export the .zip file, there is not a normal skin folder, how do I export the file into osu?

**Comment by Wieku** [comment]
What

**Comment by Liam1006** [comment]
bruh

**Comment by Liam1006** [comment]
How do I export the skin into osu?

**Comment by Wieku** [comment]
What? This is a whole application, not a skin.

**Comment by Liam1006** [comment]
oh

**Comment by Liam1006** [comment]
How do I use it then

**Comment by Liam1006** [comment]
I don't know how to add applications to osu.

**Comment by mk56-spn** [comment]
theres a wiki you numbskull https://github.com/Wieku/danser-go/wiki

**Comment by Liam1006** [comment]
I did not know there was something that said that automatically.

**Comment by Liam1006** [comment]
Oh come on

**Comment by Liam1006** [comment]
why the rick roll

**Comment by Liam1006** [comment]
does this even work or is it just a rickroll

**Comment by Wieku** [comment]
No one is your servant, also mk56-spn gave you a link
