### ISSUE TITLE
i cant run

### ISSUE THREAD

**Issue by minhlongdev** [Wieku/danser-go#219]
it said me "please update your graphic driver or your gpu"

**Comment by Wieku** [comment]
Yes, thanks for informing me that your computer is too old. At least PC specs would be appreciated... Which you deliberately omitted while submitting this issue...

**Comment by minhlongdev** [comment]
but i can run osu normaly and mc 200fps + arsenal 100 fps, so what is minium spec to run danser ?

**Comment by Wieku** [comment]
Oh yes I'm going to magically find what PC do you have from fps amount in Minecraft. Asking for the last time, PC SPECS.

Danser is not designed to be run on toasters unlike osu.
