### ISSUE TITLE
Knockout not working with map 2300606

### ISSUE THREAD

**Issue by sexyxlyWAol** [Wieku/danser-go#220]
**Describe the bug**
Knockout not working with map https://osu.ppy.sh/beatmapsets/1101236#osu/2300606

**Logs**
https://pastebin.com/57qxKFWF

**Computer configuration:**
Operating System: Windows 11
CPU: Intel i5 8300H
GPU: GTX1050ti

**Details**
The command I used was `danser.exe -knockout -id=2300606`.
After I run danser, an empty folder `9a81b8e287f9d011c0a220c979bf0292` was generated along with the folder `c42797ffa3b51181a67d5ad5624d765c` with replay files in it:
![image](https://user-images.githubusercontent.com/46948123/147196723-1f110023-5512-4631-9b00-977e22355af4.png)

Knockout works fine with several other maps I tried.
Configuration, replay and log files: https://drive.google.com/drive/folders/15KwKHefwZUKrTOSHSe-n8c-xbguconOl?usp=sharing

**Comment by sexyxlyWAol** [comment]
I copied the replay files into folder `9a81b8e287f9d011c0a220c979bf0292` and run danser agian, and the issue still existed.
The [log](https://pastebin.com/u6CMcPgK) of this attempt reported `Incompatible maps`, but that is not the real case.
![image](https://user-images.githubusercontent.com/46948123/147200143-e5e0990c-dfeb-435b-9108-2353e86ba389.png)

**Comment by Wieku** [comment]
Did you use osu!trainer on it? There's a possibility it tries to run a custom difficulty (osu!api returns nothing for the first hash). If yes - remove it and try again. osu!trainer for some reason keeps IDs so ID search can be broken afterwards

**Comment by Wieku** [comment]
Eventually try running danser with `-md5=c42797ffa3b51181a67d5ad5624d765c` instead of `-id=2300606`

**Comment by sexyxlyWAol** [comment]
Running danser with `-md5` solved the issue, thank you so much for your help.
I do not use osu!trainer, but I sometimes use McOSU client, which may also modify the maps, but I did not play this map on McOSU.
