### ISSUE TITLE
Stops read dir in config

### ISSUE THREAD

**Issue by AdisAlagic** [Wieku/danser-go#23]
Hello! I found out that if I start beatmap from local dir (where .exe is contains) it works ok. But if I start from cmd (Win+R) and write full path the game starts search in standard folder
![1](https://user-images.githubusercontent.com/26526921/66295061-23fd2380-e8f3-11e9-9f09-9cd03160cfb9.png)
![2](https://user-images.githubusercontent.com/26526921/66295073-2cedf500-e8f3-11e9-889d-ff108696b6db.png)

I also found out that Russian symbols aren't the reason.
My osu dir is D:\osu!

**Comment by Wieku** [comment]
It's because game starts in the folder you're in currently, so it tries to load assets/settings/danser.db in `C:\Users\AdisAlagic`

**Comment by Wieku** [comment]
I will see if I can fix that

**Comment by Wieku** [comment]
Will be fixed in new version of danser. Leaving this open for visibility.
