### ISSUE TITLE
danser.exe -v and several other flags don't exist

### ISSUE THREAD

**Issue by Paladynee** [Wieku/danser-go#231]
"-v" and "-version" flags don't exist which should've displayed danser's current version and exited the program.
Same with the danser "-h" and "-help" flags which should've displayed all the flags and their usage.
Don't display all commands when entered unknown flag, instead show a dialog where it says "Unknown flag -X, run 'danser -h' to see all available commands."

Reasoning behind this change: most linux based cli programs work like this.

**Comment by Wieku** [comment]
Are we talking about different danser?
* Danser already shows version when starting.
* `-h` is already implemented
* ????:
![image](https://user-images.githubusercontent.com/5307179/156924597-b0324cda-101b-473b-963a-0133add88ff3.png)

**Comment by Paladynee** [comment]
im sorry i used an old version of danser which did not have those things, my bad for not updating.

**Comment by Wieku** [comment]
...
