### ISSUE TITLE
rick rolled NANI!?

### ISSUE THREAD

**Issue by Forecatfromthecatcrew** [Wieku/danser-go#232]
**Describe the bug**
i got ricked rolled help

**Screenshots**

**Logs**
none

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by Wieku** [comment]
⠄⠄⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠄
⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠄
⠄⣤⣾⣿⠟⠋⠉⠉⠄⠈⠉⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⠿⢿⣿⡇⠄
⢰⣿⣿⣿⣤⣶⣿⣿⣿⣿⣶⡄⠄⠈⠙⣿⣿⣿⡿⠋⠁⠄⣀⣀⣤⣄⣀⠉⢣⠄
⠄⣿⣿⣿⡋⠉⠄⢀⣀⣀⣄⡀⢀⣀⣠⣿⣿⣿⡄⠄⠄⠈⠛⠛⠻⠿⢿⣆⣾⠄
⠄⣿⣿⣿⣿⣿⣦⣉⣛⣛⣩⣽⣿⣿⣿⣿⣿⣿⣿⣿⣶⠶⢶⣦⣦⠄⣀⣽⣿⠄
⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣤⣤⣶⣿⣿⣿⠄
⠄⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠄
⠄⠄⢺⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣝⢿⣿⣿⣿⣿⣿⣿⠃⢀
⡇⠄⠄⠛⢿⣿⡿⠟⣽⣿⣿⣧⡀⠄⠄⠉⠉⠙⠋⢉⣿⣧⢻⣿⣿⣿⣿⡿⣠⣿
⣷⠄⠄⠄⢀⣀⠄⠾⠿⢿⣿⣿⣿⣷⣄⣀⣀⣤⣴⣿⣿⣿⣇⠈⢿⣿⡟⢁⣿⣿
⣿⡄⠄⠄⠠⢿⣆⠄⠄⠘⠉⠉⠉⠁⠈⠙⠩⠿⠍⠙⠻⠄⠉⣰⣿⡿⠁⣾⣿⣿
⣿⡇⠄⠄⠄⠈⢿⣿⣿⣿⣶⣮⣽⣿⣿⣿⣿⣟⣋⣤⣤⣤⣴⣿⣟⣁⢸⣿⣿⣿
⣿⡇⠄⠄⠄⠄⢸⣿⣿⣿⣿⡅⠄⠄⠄⠉⠉⠉⣽⣿⣿⣿⣟⠍⢍⣴⣿⣿⣿⣿
⣿⣇⠄⠄⠄⠄⠄⠙⢿⣿⣿⣷⣦⣄⣀⣀⣤⣴⣿⣿⣿⡿⢟⠄⣼⣿⣿⣿⣿⣿
