### ISSUE TITLE
Danser -play prefix not receiving tablet output

### ISSUE THREAD

**Issue by qwertyuiothyyt** [Wieku/danser-go#233]
**Describe the bug**
My tablet doesnt work with the -play mode on danser, mouse only works.

**Screenshots**
![image](https://user-images.githubusercontent.com/52452452/158511663-2834b270-3c75-4ef5-b5ba-e31f3444672f.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/8258683/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5 4440
GPU: GT1030
Sound Card: Realtek Sound Card

**Comment by qwertyuiothyyt** [comment]
DANSER menu is the one that's interfering with the tablet output Lol.

**Comment by Paladynee** [comment]
im no developer but danser shouldn't be messing with your tablet input. are you sure its an issue with danser?

**Comment by Wieku** [comment]
Yeah, I'm using OTD as well and danser works normally. Make sure you have `Input.MouseHighPrecision` set to `false` because it doesn't work with tablets, obviously.
