### ISSUE TITLE
danser crashes when processing a 'break' before the beatmap starts

### ISSUE THREAD

**Issue by Loominagit** [Wieku/danser-go#239]
**Describe the bug**
I don't know how to explain this clearly, but if you play a map that has 'skip' button (or whatever you call) in the beginning, it just crashes.
If you give it a moment to load, the audio plays but it just stuck at loading screen and not long after it, danser crashes.

**Screenshots**

![image](https://user-images.githubusercontent.com/35314624/165477115-6864069b-ede9-4fb0-85e2-809b0b57f1d7.png)
(full log below)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/8570256/danser_crash_log.log) -- crash log upon loading the last replay on the attachment

**Attachments**
https://drive.google.com/drive/folders/16he9GLxUuuFhBsA4n5erUqwzUWnm9nk6?usp=sharing -- replays that i used on danser

**Computer configuration:**
OS:  Microsoft Windows 8.1 Pro 6.3.9600 Build 9600
CPU: AMD A4-5000 APU with Radeon(TM) HD Graphics, 4 cores
GPU: Radeon HD 8330
RAM: 1.7 GiB

**Comment by Wieku** [comment]
Skin is too heavy. Use lighter skin.

**Comment by Loominagit** [comment]
I guess you're right, thanks!
