### ISSUE TITLE
storyboards elements sometimes are transparent

### ISSUE THREAD

**Issue by nolife99** [Wieku/danser-go#240]
**Describe the bug**
Some storyboard elements are transparent even if there is a full fade cmd (F,0,0,,1) or no fade command at all. By default, commands without fade are not transparent

**Screenshots**
Here is the screenshot of the sb in danser
![Screenshot (5)](https://user-images.githubusercontent.com/89430659/166228231-9b5774ea-250c-4c9a-b6c7-7c7d02bcfc14.png)

Here is the screenshot of the same SB (same time) in osu!
![Screenshot (6)](https://user-images.githubusercontent.com/89430659/166228299-6f8c6cd7-31db-4a63-8949-d808b390c0a6.png)

also the map for testing purposes
https://osu.ppy.sh/s/1054045

The black pixels in danser are transparent while the black pixels in osu! are completely faded in.

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/8602556/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5-10500H
GPU: NVIDIA GeForce GTX1650 (Max-Q)

**Comment by Wieku** [comment]
It doesn't look like the same time, actually.

**Comment by nolife99** [comment]
sorry I used osu lazer's skip feature (on the strain graph in the overlay)

**Comment by Wieku** [comment]
Objects want to disagree. Found the issue but next time issue will be just closed if screenshots aren't taken within milliseconds

**Comment by Wieku** [comment]
Also lazer is not the best ground truth at the moment

**Comment by Wieku** [comment]
Fixed in dev branch
