### ISSUE TITLE
slider body white outline?

### ISSUE THREAD

**Issue by naminened** [Wieku/danser-go#241]
I don't know how make a white outline since I am using a black slider and the background is black. I'm tryna copy how the "Sound Chimera" sliders and notes are because it looks cool. I can't find the option to make a outline with a custom color, help please?

**Comment by PercyDan54** [comment]
https://github.com/Wieku/danser-go/wiki/Objects

**Comment by naminened** [comment]
excuse me, outeralpha and the other thing that i forgot of doesn't display a white outline across the slider body.

**Comment by naminened** [comment]
what outeralpha and outeroffset should i use to get an outline? my brain is small as heck

**Comment by sbrstrkkdwmdr** [comment]
thats for the body (inside) of the slider.
better to ask in helpdesk btw https://wieku.me/lair
