### ISSUE TITLE
Recording - Permission Denied

### ISSUE THREAD

**Issue by fadersc** [Wieku/danser-go#247]
I tried installing ffmpeg locally and in PATH, I still get this messages:
- C:\Users\Fader\Desktop\danser\videos\danser_2022-06-07_21-10-09_temp\video.mp4: Permission denied
- C:\Users\Fader\Desktop\danser\videos\danser_2022-06-07_21-10-09_temp\audio.mp4: Permission denied
Screenshot:
![image](https://user-images.githubusercontent.com/107073894/172462705-329302e6-3d0b-4c6b-acdc-c0ec88d005e5.png)

**Comment by milena-kos** [comment]
check if you have enough storage space

**Comment by Wieku** [comment]
> check if you have enough storage space

It's not storage space.

@fadersc Do you have any antivirus software?

**Comment by fadersc** [comment]
Yeah I had Avast.
Disabled it, works now. Thank you so much!
