### ISSUE TITLE
"Beatmap with exact parameters not found"

### ISSUE THREAD

**Issue by sleepydream431** [Wieku/danser-go#249]
**Describe the bug**
Beatmap not found? i have setup danser with ffmpeg, imported my beatmaps and i'm getting this error
"Beatmap with exact parameters not found"

**Screenshots**

![Beatmapnotfound](https://user-images.githubusercontent.com/107746718/174473578-68d04f6b-235b-4234-b191-c382c9069146.PNG)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/8935030/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 9700K

**Comment by xTunio** [comment]
Try putting difficulty without square brackets

**Comment by sleepydream431** [comment]
> Try putting difficulty without square brackets

Thank you, that worked for me 👍, for some reason wont show that it's DT though it plays like it's nomod

**Comment by milena-kos** [comment]
you can close the issue if it is resolved
