### ISSUE TITLE
Failed to import a map

### ISSUE THREAD

**Issue by xd-mau5** [Wieku/danser-go#254]
**Describe the bug**
Failed to import: 1641821 Hoshimi Production - IDOLY PRIDE (TV Size)\audio.osu
This also happen trying to use danser-launcher, even downloading the map again keeps happening

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/9015759/danser.log)
[launcher.log](https://github.com/Wieku/danser-go/files/9015761/launcher.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5 6200u

**Comment by Wieku** [comment]
It just means map file is empty/broken. Just ignore

**Comment by Wieku** [comment]
To clarify: "audio.osu" means that's it's not a normal map file, it's probably a leftover when the map was WIP. osu! sometimes just 0 bytes the file instead of removing it during update.

Redownloading won't fix that message, you have to remove that audio.osu file manually.
