### ISSUE TITLE
ffmpeg encoder preset error

### ISSUE THREAD

**Issue by RugiSerl** [Wieku/danser-go#255]
**Describe the bug**
Recently I got an ffmpeg crash during a record attempt, and It was apparently caused by the encoder settings
I am using the latest release of danser (0.7.0) and the encoder is h264_nvenc.
For this encoder, it looks like ffmpeg accepts presets like "fast, slow, medium..." but danser automatically set those values to "p3, p5, p4...". So I fixed this by editing directly the setting file. I don't know if it is a problem caused by a different version of ffmpeg though.

**Screenshots**

![image](https://user-images.githubusercontent.com/77239970/176670740-0e232c6f-c580-40a1-82e2-899554a1684e.png)

![image](https://user-images.githubusercontent.com/77239970/176672583-ee940ea4-2a77-49da-b766-f222b854a1bc.png)

![image](https://user-images.githubusercontent.com/77239970/176685139-c074059a-a170-4dc8-9421-06c28682100e.png)

**Computer configuration:**
using ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers built with gcc 9.3.1 (GCC) 20200621
Operating System: Windows 10
GPU: GTX 1650 mobile

**Comment by Wieku** [comment]
You have fast,medium,slow marked as legacy, they should work.
You have gtx 1650, iirc you need at least ffmpeg 4.4 to use p* presets. p presets won't work on old gpus supporting nvenc

**Comment by RugiSerl** [comment]
Ok thank you :)
