### ISSUE TITLE
Cannot disable custom beatmap sounds

### ISSUE THREAD

**Issue by EmanDev** [Wieku/danser-go#26]
`"Audio": {
		"GeneralVolume": 0.5,
		"MusicVolume": 0.5,
		"SampleVolume": 0.5, // when I set to 0 skin hitsounds are muted
		"Offset": 0,
		"IgnoreBeatmapSamples": true,
		"IgnoreBeatmapSampleVolume": true
	}`

**Comment by Wieku** [comment]
More info? video?

**Comment by EmanDev** [comment]
> More info? video?

I will reproduce it now. 

I'll edit this reply later.

**Comment by Wieku** [comment]
It's already fixed in development code. Wait for the next release.
Leaving this open for visibility for now.

**Comment by EmanDev** [comment]
Well for now, we can just remove the custom beatmap sounds and put them back after. Only if it's not hassle to the user.
