### ISSUE TITLE
Strain graph looks weird when you customize it

### ISSUE THREAD

**Issue by FlashlightXi** [Wieku/danser-go#261]
**Describe the bug**
Setting the configuration like this make the strain graph look weird.
![image](https://user-images.githubusercontent.com/50948856/179578232-a7c1a5e1-7462-41b9-aaec-2e285f9c1c6b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/50948856/179578050-aba67363-3db9-4bf2-9c80-cf49873e60fb.png)

**Computer configuration:**
Operating System: Windows 11
CPU: Intel i7 10700
GPU: RTX 3060 Ti

**Comment by Wieku** [comment]
danser's screen is 1366x768 (for 16:9), similar to osu. That's theoretical maximum size for the graph and 
as well as maximum position.

Will investigate anyways because making it bigger shouldn't break.

**Comment by Wieku** [comment]
Fixed in development branch.
