### ISSUE TITLE
Spinner movers don't work as intended 

### ISSUE THREAD

**Issue by Tripticon84** [Wieku/danser-go#264]
The [square](https://youtu.be/zNe1UAStbzI), [triangle](https://youtu.be/SgbCKbj9Mmc) and [heart](https://youtu.be/PnGyShTlieA) spinner movers, rotate around the centre, whereas in previous versions this was not the case. This makes it unpleasant to look at.

**Comment by Wieku** [comment]
I can't reproduce this. Most probably you're using "pippi" mover which does affect spinners, since the start.

**Comment by Tripticon84** [comment]
Indeed it was the mover pippi. Thank you for the precision.
