### ISSUE TITLE
Launcher crashed because no executable file in %!P(MISSING)AT H%!(NOVERB)

### ISSUE THREAD

**Issue by pat284956** [Wieku/danser-go#265]
**Describe the bug**
When I always render anything and finish, it gives an error that the launcher crashed because an executable file is missing and closes when I close the error message
**Screenshots**
(https://user-images.githubusercontent.com/49976368/180625400-a8ecde74-0296-412f-8ae1-cc4184943e77.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/9174800/danser.log)

**Computer configuration:**
Operating System: Windows 11
CPU: Intel i7 1165G7
GPU: Intel iRIS Xe Graphics

**Comment by Wieku** [comment]
It's the "show exported videos in explorer" crashing. Video itself should be fine.

Still weird tho

**Comment by Wieku** [comment]
Closing this as a weird Windows 11 quirk
