### ISSUE TITLE
[Proposal] Add argument for specifying path to beatmap

### ISSUE THREAD

**Issue by awful-coder** [Wieku/danser-go#266]
AFAIK and according to the creator of danser-go, there is no way to simply use a beatmap at a certain path.
This is a problem because specifying paths could be useful in some cases:
- In the absence of an osu! installation (e.g. with McOsu I think) or with multiple osu installations (although this could be solved somewhat with different settings files)
- When its location is already known, avoiding the overhead of finding the beatmap
  - When using a custom algorithm to determine which beatmap to use
- Opening beatmaps e.g. from the file manager (with e.g. a custom .desktop file) which could be useful for e.g. previewing maps I guess?

To solve this problem, an argument such as "beatmap" could be added which would allow specifying the path to the beatmap.
Also preferably following symlinks to backgrounds etc.

**Comment by Wieku** [comment]
Already denied in #228 

Too much of a hassle to add, honestly. Danser can work without osu! as long as you keep Songs folder in stable's hierarchy. Danser can even unpack .osz by itself.

You should use GUI. If you're making a script, you can calculate md5 hash of the .osu file and then launch danser with `-md5` flag. Or with `-id`, if map id is bigger than 200000-ish.
