### ISSUE TITLE
Invalid character after objedct key.

### ISSUE THREAD

**Issue by sonicdude12305** [Wieku/danser-go#267]
So I've been trying to get saberstrike old as my normal skin, but it keeps on telling me that there is an invalid character, And i don't kn ow how to fix. thx in advance.

**Comment by sonicdude12305** [comment]
Operating system windows 11
Computer Some model HP Pavillion.

**Comment by Wieku** [comment]
Then it means you edited JSON file incorrectly, please use launcher
