### ISSUE TITLE
Backround/all colors have a slight green tint

### ISSUE THREAD

**Issue by Atirtra** [Wieku/danser-go#268]
So I recorded a replay of mine of Everything Will Freeze.
The background of the map is supposed to be black and white, but the whites get this weird green tint which is more visible the more dim the bg is. I am not sure if all colors are tinted or just the bg
This bug is present even with default settings
Tried with numerous codecs and color formats, only danser 6.9.0 has correct colors

danser v7 log:
https://github.com/Wieku/danser-go/files/9263063/danser.log

danser v6 log:
https://github.com/Wieku/danser-go/files/9263105/danser.log

Green tint with danser v7
https://user-images.githubusercontent.com/110634509/182944587-faa3a599-91cd-4c14-8a12-da665c12e952.mp4

No tint with v6
https://user-images.githubusercontent.com/110634509/182945660-6a9c85dc-e422-4fb4-a80f-4ac4180f2116.mp4

PC Specs if it helps:
Operating System: Windows 11
CPU: Ryzen 5 5600G
GPU: GTX 1660 Super

**Comment by Wieku** [comment]
Can you send me the replay and settings?

**Comment by Atirtra** [comment]
Settings
https://github.com/Wieku/danser-go/files/9263297/default.txt

Replay
https://cdn.discordapp.com/attachments/817748038868533306/1004855633629171832/Atirta_-_UNDEAD_CORPORATION_-_Everything_will_freeze_Extra_2022-08-04_Osu.osr

**Comment by Vortex100K** [comment]
I think this happens with anything using ffmpeg, around 2 months ago I ran into the same problem with a replay I was recording and it had a green tint, I fixed it by using colour correction but it made the whole video feel a bit weird 
Just thought I would share this info :)

**Comment by Wieku** [comment]
Nah it was an issue with danser since 0.6.9 worked ok

**Comment by Vortex100K** [comment]
okay
