### ISSUE TITLE
Option to Render to .mp4

### ISSUE THREAD

**Issue by MasterZitron** [Wieku/danser-go#27]
Using ffmpeg to render stuff to a video file would probably work better than real-time, that way my pc won't suffer when turning on bloom.

**Comment by GamingInfinite** [comment]
This would also reduce the amount of dropped frames in watching it, because it would be prerendered

**Comment by Wieku** [comment]
danser is intended to be realtime, too much work at least for now.

**Comment by Wieku** [comment]
I'm withdrawing my last comment

**Comment by Wieku** [comment]
It can be tested in in dev branch
