### ISSUE TITLE
Weird artifacts even tough everything went fine in denser.

### ISSUE THREAD

**Issue by paffff262** [Wieku/danser-go#272]
There are  some weird artifacts when the video is done. Like in the screenshot there are more artifacts like that there. Is it some option that I don't understand or is it a bug or even something else.

![image](https://user-images.githubusercontent.com/61905006/184516922-8dbc2c90-9b9e-4c6c-9243-99b960827209.png)

ty for any help

Computer configuration:
Operating System: Windows 11 Pro
CPU: Intel i5 10400f
GPU: RTX 2070

**Comment by Wieku** [comment]
Use motion blur instead of setting FPS
