### ISSUE TITLE
Changing the license to GPLv3

### ISSUE THREAD

**Issue by Wieku** [Wieku/danser-go#275]
As danser is not a library, but an end-user software, having it under MIT makes danser vulnerable to abuse. We've had instances of people only changing the logo/name and calling it **THEIR OWN PROPRIETARY** program, which is okay license-wise, but meh morality-wise.

That's why I propose changing the license to GPLv3 going forward. It will also allow bundling danser with ffmpeg, which will make setting up danser much easier for people who are not very proficient in operating computers.

To make this change, I need approval from code contributors:

- [x]  @Wieku (2,008 commits)
- [x] @vladaad (9 commits)
- [x] @TechnoJo4 (7 commits)
- [x] @PercyDan54 (2 commits)
- [x] @khang06 (1 commit)
- [x] @jamiegyoung (1 commit)

**Comment by TechnoJo4** [comment]
Wieku desires to offer danser-go, which may include contributions made under this GitHub account (the "Contributions"), under the GPLv3 License. By this agreement, I authorize Wieku to use, modify and/or distribute the Contributions, in whole or in part, under the GPLv3 License.

I certify that the Contributions were created in whole by me, the owner of this GitHub account, and I have the legal right to authorize Wieku to use the Contributions as set forth in this agreement.

**Comment by vladaad** [comment]
Wieku desires to offer danser-go, which may include contributions made under this GitHub account (the "Contributions"), under the GPLv3 License. By this agreement, I authorize Wieku to use, modify and/or distribute the Contributions, in whole or in part, under the GPLv3 License.

I certify that the Contributions were created in whole by me, the owner of this GitHub account, and I have the legal right to authorize Wieku to use the Contributions as set forth in this agreement.

**Comment by khang06** [comment]
Wieku desires to offer danser-go, which may include contributions made under this GitHub account (the "Contributions"), under the GPLv3 License. By this agreement, I authorize Wieku to use, modify and/or distribute the Contributions, in whole or in part, under the GPLv3 License.

I certify that the Contributions were created in whole by me, the owner of this GitHub account, and I have the legal right to authorize Wieku to use the Contributions as set forth in this agreement.

**Comment by PercyDan54** [comment]
Wieku desires to offer danser-go, which may include contributions made under this GitHub account (the "Contributions"), under the GPLv3 License. By this agreement, I authorize Wieku to use, modify and/or distribute the Contributions, in whole or in part, under the GPLv3 License.

I certify that the Contributions were created in whole by me, the owner of this GitHub account, and I have the legal right to authorize Wieku to use the Contributions as set forth in this agreement.

**Comment by jamiegyoung** [comment]
Wieku desires to offer danser-go, which may include contributions made under this GitHub account (the "Contributions"), under the GPLv3 License. By this agreement, I authorize Wieku to use, modify and/or distribute the Contributions, in whole or in part, under the GPLv3 License.

I certify that the Contributions were created in whole by me, the owner of this GitHub account, and I have the legal right to authorize Wieku to use the Contributions as set forth in this agreement.
