### ISSUE TITLE
video starting sooner than map

### ISSUE THREAD

**Issue by norwexy** [Wieku/danser-go#278]
video for the map: https://osu.ppy.sh/beatmapsets/1503327#osu/3079907 starts sooner than its suppsed to

danser: https://imgur.com/a/OmWro9m
osu: https://imgur.com/a/1tVkk7u

[danser.log](https://github.com/Wieku/danser-go/files/9438671/danser.log)

OS: Windows 11
CPU: Intel i5 9400F

**Comment by Wieku** [comment]
If I remember correctly that map was unfixable in danser for some reason.
Will look into it again but may be a #nofix

**Comment by Wieku** [comment]
Oh just noticed this map is broken as well in osu!lazer

**Comment by Wieku** [comment]
I found the issue, will be fixed in next release
