### ISSUE TITLE
Error message from starting launcher

### ISSUE THREAD

**Issue by DeenyBoi** [Wieku/danser-go#279]
**Describe the bug**
nothing specific about it, there's an error message (see pic below) that appeared as I ran danser-launcher.exe.
apparently this doesn't work if I don't have a gpu

(lmk if I forgot something (since I'm kind of stupid))

**Screenshots**
![image](https://user-images.githubusercontent.com/57526976/187444360-314d289f-283e-430a-bf33-a974c15ecede.png)

**Logs**
[launcher.log](https://github.com/Wieku/danser-go/files/9452995/launcher.log)

**Computer configuration:**
Operating System: Win10
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by Wieku** [comment]
I think it shouldn't be a surprise that a 10 YEAR OLD laptop is not able to run a modern application.
