### ISSUE TITLE
Danser can't hit invisible hitcircles

### ISSUE THREAD

**Issue by Joystickplays** [Wieku/danser-go#280]
**Describe the bug**
Danser can't hit invisible hitcircles, which is used on most aspire maps. Often, these invisible circles are usually sliders.

**Screenshots**
![image](https://user-images.githubusercontent.com/61606869/188384695-e7f40340-4509-44a7-9062-4985469a3326.png)
![image](https://user-images.githubusercontent.com/61606869/188384740-63fbd295-0e27-43c7-a81f-2b911241e920.png)

**Logs**
https://hastebin.com/ituvilokuk.yaml

**Computer configuration:**
Operating System: Windows 11
CPU: i3-1005G1

**Comment by Wieku** [comment]
Already fixed in dev branch
