### ISSUE TITLE
Problems with Background/Storyboard

### ISSUE THREAD

**Issue by EpicJosch** [Wieku/danser-go#281]
So i dont know if its the Background or the Storyboard but one of them are slightly moved so when there is a circle in the background of the map the cursor dont click it but clicks besides the circle. I think the background is wrong sized or moved i hope you can help me!

**Comment by Wieku** [comment]
In Playfield settings there is an option to "move Playfield to look like osu!".
In stable, playfield is slightly moved downwards, but in danser is centered by default, so some storyboards are misaligned.

**Comment by EpicJosch** [comment]
Okay thanks for the response! I'll try that later!

**Comment by EpicJosch** [comment]
Still the same issue with this option enabled

**Comment by Wieku** [comment]
I can't do more without seeing examples

**Comment by Wieku** [comment]
Like you literally ignored the issue template that asks for screenshots

**Comment by EpicJosch** [comment]
Sry don't really know how GitHub works.. I will pass over some examples

**Comment by EpicJosch** [comment]
So i have a shared folder here for you with a part of the video i try to generate with Danser, some informations about danser and the danser config im using. In the video you can see that the danser doesnt click the right points when it comes to this arrows in the video.

--> https://epic-josch.de/nextcloud/index.php/s/47gePXA3K7eSm28

**Comment by Wieku** [comment]
Ohhhhhh, it's kind of funny, I got the same issue like 10 minutes ago :P
Set Parallax Amount to 0.
Will be fixed in next release

**Comment by EpicJosch** [comment]
That fixed it. Thanks for the response! :)
