### ISSUE TITLE
Launcher crashed with message

### ISSUE THREAD

**Issue by Kaedo17** [Wieku/danser-go#284]
when opening danser.exe it's crashing, idk why. It's newly installed
Operating System: Windows 10
CPU: Intel i5 2450M
![Screenshot (222)](https://user-images.githubusercontent.com/92620393/192265137-fc2ed526-60ce-4fcb-9c8a-1b5f1f8da48d.png)

**Comment by Wieku** [comment]
Your laptop is a toaster
