### ISSUE TITLE
Function keys crash danser

### ISSUE THREAD

**Issue by Joystickplays** [Wieku/danser-go#293]
**Describe the bug**
This bug can be replicated if you have an ASUS laptop. The keyboard will by default do F1-F12 commands with the `FN` key. Once one of the F1-12 buttons is pressed focusing on a danser window, it will crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/61606869/197685573-0f6ea885-610e-44c8-8269-06e77ae47807.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/9857206/danser.log)

**Computer configuration:**
Operating System: Microsoft Windows 11
CPU: Intel i3-1005G1

**Comment by Wieku** [comment]
@Joystickplays What's your keyboard layout and typing language?

**Comment by Joystickplays** [comment]
@Wieku I'm not sure of what exactly you mean, but my keyboard layout is US (QWERTY) and the typing language is English.

**Comment by FlashlightXi** [comment]
Function keys also crashes danser for me too.
I've first realized when I was configuring the system volume by a volume up key on keyboard and crashed instantly.
Hope this helps.

Windows 11, Core i7-10700, RTX 3060 Ti, 32GB (27GB were used as of recording)

https://user-images.githubusercontent.com/50948856/199078957-a1efd05b-b696-4d02-82d0-0d048bfcaf49.mp4

**Comment by Viruzaum** [comment]
Can confirm this also happens on linux:

![image](https://user-images.githubusercontent.com/23330390/199083453-99ee58e7-38cf-4187-9052-8c3fd271e3ac.png)
