### ISSUE TITLE
Some sliders don't match stable precisely.

### ISSUE THREAD

**Issue by Paladynee** [Wieku/danser-go#294]
**Describe the bug**
A slider with gray anchor points may not match stable exactly.
I don't think this bug is caused by `Gameplay.Objects.Sliders.Quality.PathLevelOfDetail` since I have it set on 800 and it was the same with 200.

**Danser version**
0.8.1

**Screenshots**
Danser is overlayed on top of stable with lower opacity.
https://user-images.githubusercontent.com/62181440/198896338-87b8b25a-63c9-4673-844d-0d34f28328be.mp4
Red is stable, gray is danser.
![image](https://user-images.githubusercontent.com/62181440/198896360-5d8343cd-3ea8-4e4e-a732-f37654b1bae0.png)

**Map**
Here's the map which has a slider with a lot of anchor points (accelerating/decelerating slider created by Mapping Tools).
https://www.mediafire.com/file/cbgtgn0vjoo07hp/Syko+-+BrooklynBloodPop.osz/file

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i3 10100F
GPU: GTX1050 Ti

**Comment by Wieku** [comment]
> accelerating/decelerating slider created by Mapping Tools
That's your answer.
Don't make stupid sliders

**Comment by Wieku** [comment]
Slider should calculate correctly but rendering have sanity levels and sliders like these exceed them.

**Comment by Paladynee** [comment]
> Slider should calculate correctly but rendering have sanity levels and sliders like these exceed them.

are there any ways to change this sanity level?
