### ISSUE TITLE
Need help, how do fix this bass issue?

### ISSUE THREAD

**Issue by Loominagit** [Wieku/danser-go#295]
So, I just installed danser through the [AUR](https://aur.archlinux.org/packages/danser). I run it, and it says that 'bass' is missing from my laptop... I tried installing bass and re-run it, still got this error. How do I get rid of it?
![Screenshot_2022-11-24_20-50-19](https://user-images.githubusercontent.com/35314624/203800280-c6cb9528-eba9-455a-9fea-e725b9c08ef4.png)
![Screenshot_2022-11-24_20-51-13](https://user-images.githubusercontent.com/35314624/203800443-23df3fb0-6bbd-4287-a36e-1b91892ce4fc.png)

... and yes, I tried the pre-built binary, still got the error.

**Comment by Wieku** [comment]
Please read the issue. You don't have any audio driver, there's nothing wrong with bass.
