### ISSUE TITLE
Can't watch replay of maps with special characters in their title

### ISSUE THREAD

**Issue by kwotacode** [Wieku/danser-go#296]
Maps like [this one ](https://osu.ppy.sh/beatmapsets/1011739#osu/2117567) are unable to be loaded normally using a replay, I imagine due to the restrictions of special characters in file names

![image](https://user-images.githubusercontent.com/80002984/204104117-f36bc527-236d-4822-bd0f-88cb9e46c264.png)
![screenshot374](https://user-images.githubusercontent.com/80002984/204104158-9b955f3d-ee76-47c9-8939-928bec33a6e7.jpg)

**Log**
[danser.log](https://github.com/Wieku/danser-go/files/10096828/danser.log)

Operating System: Windows 10

**Comment by Wieku** [comment]
Replays have to be made on the exact version of the map. It's a pending map so no wonder it breaks.
