### ISSUE TITLE
Danser doesnt show accuracy numbers over scorebar asset from skin

### ISSUE THREAD

**Issue by MelonIs45** [Wieku/danser-go#301]
**Describe the issue:**
Danser doesn't display accuracy over `scorebar-bg.png` on the skin

Example in danser:
![image](https://user-images.githubusercontent.com/45884578/205467045-2c14fc8e-06a1-44c6-aa59-87ab5750607c.png)

Example in osu!:
![image](https://user-images.githubusercontent.com/45884578/205467051-cd8f2e8d-5f4f-4341-94d4-4e44094e8c2e.png)

Danser log maybe:
[danser.log](https://github.com/Wieku/danser-go/files/10147548/danser.log)

 `scorebar-bg@2x.png` that I used to test
![scorebar-bg@2x](https://user-images.githubusercontent.com/45884578/205466993-b1eeb070-6f7b-4b0e-b85c-4ed02779a375.png)

**Hardware Info**
Operating System: Windows 11
CPU: AMD R9 6900HS
GPU: Nvidia RTX 3070ti Mobile

**Comment by Wieku** [comment]
osu! cutting edge has a different display order.
