### ISSUE TITLE
replays from osu!lazer dying

### ISSUE THREAD

**Issue by Axilotl17** [Wieku/danser-go#302]
**Describe the bug**
I'm trying to record a replay done in lazer, and because HP is different in lazer, danser stops when they would have died in stable, while in lazer they wouldn't yet have died. I do want the notelock to happen, Its just I want it to continue recording after "death".

I realize this is only applicable to a narrow set of problems but It would be a tiny fix to just... allow enabling of recording after death. 

**Screenshots**
N/A

**Logs**
N/A

**Computer configuration:**
N/A

**Comment by Axilotl17** [comment]
also spinners auto-fail you

**Comment by 2Tsk2** [comment]
ill bump this

**Comment by Wieku** [comment]
> ill bump this

This is not a forum.

**Comment by 0xallie** [comment]
This seems to happen even if you use the classic mod in lazer.
