### ISSUE TITLE
I got this error while preparing 

### ISSUE THREAD

**Issue by WrYLYUd** [Wieku/danser-go#305]
![ss](https://user-images.githubusercontent.com/121301989/209351719-ca640df5-0140-4d14-9583-cb33ecdebdc1.png)

![image](https://user-images.githubusercontent.com/121301989/209351811-41690533-a9a1-4c4f-b78a-91a90af0f076.png)

**Comment by WrYLYUd** [comment]
plz help

**Comment by Wieku** [comment]
Don't ignore issue template then I *may* be able to help.
