### ISSUE TITLE
GUI broke (issue template)

### ISSUE THREAD

**Issue by yeaa132** [Wieku/danser-go#307]
**Describe the bug**
I opened Danser, and the GUI broke!

**Screenshots**
![2022-12-25 (9)](https://user-images.githubusercontent.com/77181802/209486828-dedd5b4a-d218-42ca-b33e-ace90015f238.png)

**Logs**
2022/12/25 19:32:27 -------------------------------------------------------------------
2022/12/25 19:32:27 danser-go version: 0.8.3
2022/12/25 19:32:27 Ran using: [D:\my name\Stuff\Downloads\danser-0.8.3-win\danser-cli.exe]
2022/12/25 19:32:27 OS:  Microsoft Windows 10 Home 10.0.19045 Build 19045
2022/12/25 19:32:27 CPU: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz, 4 cores
2022/12/25 19:32:27 RAM: 16 GiB
2022/12/25 19:32:27 -------------------------------------------------------------------
2022/12/25 19:32:27 Checking Github for a new version of danser...
2022/12/25 19:32:27 You're using the newest version of danser.
2022/12/25 19:32:27 No beatmap specified, closing...
2022/12/25 19:32:27 SettingsManager: Loading "D:\my name\Stuff\Downloads\danser-0.8.3-win\settings\default.json"
2022/12/25 19:32:27 SettingsManager: "D:\my name\Stuff\Downloads\danser-0.8.3-win\settings\default.json" loaded!
2022/12/25 19:32:27 ApiConnector: Loading "D:\my name\Stuff\Downloads\danser-0.8.3-win\settings\credentials.json"

**Computer configuration:**
Operating System: Windows 10 22H2
CPU: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz   3.40 GHz (if it's a graphics issue)
GPU: Geforce GTX 1050Ti (if it's a graphics issue)

**Comment by Wieku** [comment]
* please describe the issue, I'm not a magician 
* please upload the file, as template asks for
* please don't open new issues, next one will be a ban.

**Comment by REALCraylenGD** [comment]
Very deeply sorry, it was a graphics issue, and I needed to update my GPU.
