### ISSUE TITLE
No skip intro setting

### ISSUE THREAD

**Issue by yeacark** [Wieku/danser-go#310]
Just updated to the latest version of danser and i cannot find any option to skip the intro of a map automatically

screenshot: 
![immagine](https://user-images.githubusercontent.com/111182808/211652878-49957ee9-f2d4-48d9-9cfa-84576220fec1.png)

**Comment by M3IY0U** [comment]
Skipping the map isn't saved in the config, hence it's not in the config editor. What you're looking for is under Time/Offset in the main menu
