### ISSUE TITLE
Encoder for AMD

### ISSUE THREAD

**Issue by SonThanhVN** [Wieku/danser-go#311]
i currently using an AMD GPU
but there seem to be no Encoder for it
is there gonna be a Encoder for AMD GPU ?

**Comment by imsuck** [comment]
https://github.com/Wieku/danser-go/wiki/Recommended-encoding-settings#amd
Wiki is your friend

**Comment by Wieku** [comment]
AMD encoder is very bad, support for it was dropped completely.
