### ISSUE TITLE
Replay fails even when stable doesnt

### ISSUE THREAD

**Issue by MelonIs45** [Wieku/danser-go#316]
**Describe the bug**
Replay fails even when stable doesnt

**Video**
https://user-images.githubusercontent.com/45884578/220459014-76085a41-bfbf-47b7-ac90-c01ead7ea577.mp4

**Replay**
https://meloons.xyz/osu/files/waldschrein.osr (github doesnt allow osr)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/10797779/danser.log)

**Comment by cyperdark** [comment]
Change ``IgnoreFailsInReplays`` to true in your settings file

Note: Download latest version if you dont have ``IgnoreFailsInReplays`` field in json settings file
