### ISSUE TITLE
Is it possible to set the osu sonngs dir to a cloud index?

### ISSUE THREAD

**Issue by phantomic12** [Wieku/danser-go#322]
I'm trying to deploy danser in multiple cloud instances with space constraints, I was curious as to whether it is possible to set the songs directory to say a onedrive index, one example of such listed below:

https://drive.swo.moe/

Any advice is much appreciated!

**Comment by Wieku** [comment]
Never dabbled in anything like this, but I guess you would need to mount OneDrive as Network Location. Be aware though that danser building it's database will basically download all .osu files to build checksums.

**Comment by phantomic12** [comment]
As far as I know, downloading the .osu files shouldnt be too much of an issue, as they arent the real space consumers.

What I should've asked first is if its possible to retrieve songs from an api such as beatconnect, similarly to https://github.com/MasterIO02/ordr-server


The idea would be to primarily retrieve beatmaps from beatconnect and use the remote mirror as a fallback.

I am looking to write a shell script to render an osr without storing the entire beatmap database locally. I've looked into using ordr, but it's too complicated for what I want to achieve, which is to simply render an mp4 from an osr using a preexisting set of render settings.
