### ISSUE TITLE
Failed to run BASS, error id: 3, message: Can't find a free/valid driver

### ISSUE THREAD

**Issue by Quicksoapy** [Wieku/danser-go#324]
When attempting to launch the program, it has a runtime error:
`
Launcher crashed with message: Failed Failed to run BASS, error id: 3, message: Can't find a free/valid driver`
`

I am running Linux Mint 21.1. I have updated my graphics driver only days ago (AMD rx 6750xt)

**Comment by Quicksoapy** [comment]
Update: i used 0.7.1, which worked fine. I have the feeling the GUI breaks.

**Comment by HMMMTH** [comment]
Bruh look at the issue I opened on this.

**Comment by HMMMTH** [comment]
Also just to make this clear Wieku this BASS error is probably a problem with danser because it makes no sense that every other application except danser is able to access my sound card through BASS.

**Comment by Quicksoapy** [comment]
reinstall fixed it
