### ISSUE TITLE
Fails to load a beatmap when a change is detected

### ISSUE THREAD

**Issue by FlashlightXi** [Wieku/danser-go#327]
**Describe the bug**
I started up danser and tried to encode something, and it worked.
But after I saved an edited beatmap which danser detects a file change and applies it and tries to encode them, seems like danser can't find an edited beatmap (which is the same beatmap as I encoded after start-up) and returns nothing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50948856/236266112-404fce4b-0de2-4b5b-a36f-1543878f0d76.png)

**Logs**
![image](https://user-images.githubusercontent.com/50948856/236266043-77483f48-65d6-4b35-b0f5-02cea264459a.png)

**Computer configuration:**
Operating System: Windows 11
CPU: Intel i7 10700

**Comment by Wieku** [comment]
It won't load updated maps if you have "Speed up startup on Slow HDDs" launcher option selected. That option warns you about it.
