### ISSUE TITLE
Reverse Arrow Rotation

### ISSUE THREAD

**Issue by siblinghood** [Wieku/danser-go#328]
**Describe the bug**
Reverse arrow rotated into the wrong direction multiple times on straight sliders.

**Screenshots**
![aJzA8gi](https://user-images.githubusercontent.com/132373870/236643395-c1dc67b1-a6cd-4e0a-8c94-d75279b2f546.png)
at 1:13 and 1:18 in [o!rdr replay](https://link.issou.best/NzFG4x)

**Logs**
I did not do the rendering, so I do not have this.  The renderer on o!rdr is listed "Phil's PC 3"

**Computer configuration:**
Phil's PC 3

**Comment by PercyDan54** [comment]
The only weird thing I can see is the bugged "straight" slider is a Bezier slider:
`256,256,110674,2,0,B|256:256|256:352,3,70`
`256,128,117531,2,0,B|256:128|256:32,3,70`

Changing them to Linear works around this issue

**Comment by Wieku** [comment]
@PercyDan54 thanks for the info, will see what happens under the hood
