### ISSUE TITLE
Universal offset does nothing in recordings

### ISSUE THREAD

**Issue by Atirtra** [Wieku/danser-go#331]
At least since danser v0.7.0 not sure about older versions, universal offset has done nothing with recordings. To my ear, the hitsounds feel like they are a bit too early so I'd like to use an offset of -30ms which I also use in game. Tested with -300ms and 300ms, nothing changed. Is this behavior intended or simply an oversight?

**Log**
[danser.log](https://github.com/Wieku/danser-go/files/11721783/danser.log)

Shouldn't be a hardware problem, this has been applicable on every system of mine.

**Comment by AliceUnderwater** [comment]
intended functionality, recordings should place hitsounds at exactly the right time no matter what, so offset issues are typically related to the map itself being off (based off what Wieku has said)

**Comment by Wieku** [comment]
> so I guess this is a "me" problem?

If you need -30ms on every hardware then I would assume so. Or there's a common hardware link (like terrible keyboard or mouse) which makes your ear accustomed to latency so no-latency then feels wrong.

Global offset is used to offset hardware latency which doesn't happen in record mode. If there's an issue with the map itself, use Time/Offset -> Audio offset.

But if you're intending to share the video it's best to keep offsets original (unless you see online offset when looking at map info in osu! client)

**Comment by Atirtra** [comment]
> Global offset is used to offset hardware latency which doesn't happen in record mode.

"Global offset" means what here? If we're talking about osu!'s universal offset (and Danser's with that), that doesn't do anything for hardware latency, it shifts the song relative to hitsounds, so what does this mean?

> If there's an issue with the map itself, use Time/Offset -> Audio offset.

And if there's an offset problem with the map itself, doing "Time/Offset -> Audio offset" will just move all of the sound including the song to an incorrect place, when only moving the song to the hitsounds would fix it.

If this is still too much of a "me" problem then that's fine, but it would be a useful feature for some people. Cheers!
