### ISSUE TITLE
cannot load replays from osu trainer modified diff

### ISSUE THREAD

**Issue by osidufg** [Wieku/danser-go#334]
**Describe the bug**
Whenever I try to load any replay from a diff that was made by osu trainer (a software to modify beatmap's ar, od, speed, or whatever and outputs a unique diff inside a beatmap folder) it gives an error saying "Replay uses an unknown map. Please download the map beforehand"
**Screenshots**
![image](https://github.com/Wieku/danser-go/assets/89566386/b0662b7e-b30e-461b-ac43-8872774a8811)

![image](https://github.com/Wieku/danser-go/assets/89566386/efeb4e1b-a46e-4cad-ac3f-e4890d05fb4d)

**Logs**
![image](https://github.com/Wieku/danser-go/assets/89566386/ec9c90fe-6a7d-4c7f-a9c5-372520c260e0)
danser.log doesn't seem to be logging anything today (1st July 2023)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i3-9100F
GPU: AMD RX580
Sound Card: none

**Comment by Wieku** [comment]
@osidufg trainer diffs should work without any issues, do you restart the launcher to load the new diffs?

**Comment by osidufg** [comment]
@Wieku Oh sorry. Apparently I checked the option "Speed up startup on slow HHDs" and so trainer diffs couldn't be loaded even after I reloaded the danser gui. It works now after I unchecked it.

**Comment by EpicJosch** [comment]
i have the same error without this option enabled and also tried deleting the whole danser database which did not solve this error
