### ISSUE TITLE
Random crashes during recording

### ISSUE THREAD

**Issue by Redstonneur1256** [Wieku/danser-go#335]
**Issue:**
Whenever I'm trying to record a replay, danser randomly stops with exit code 0xC0000005.
It also detects that I am using Windows 10 but I am actually on Windows 11.

**Computer configuration:**
Operating System: Windows 11
CPU: AMD Ryzen 7 5800H
GPU: AMD Radeon RX 6600M

[danser.log](https://github.com/Wieku/danser-go/files/11929493/danser.log)

**Comment by Wieku** [comment]
You're using h264_amf encoder, which isn't officially supported by danser so my help ends here.

**Comment by Redstonneur1256** [comment]
Encoder shouldn't cause issues at it's handled by ffmpeg and just sending frames to ffmpeg shouldn't cause any issues, also the crash also occurs when just playing the replay normally so the encoder isn't the issue

**Comment by Wieku** [comment]
@Redstonneur1256 that's an issue with pre 23.7.1 drivers. Driver update will cause another issue mentioned in #337 which will be fixed in danser 0.8.5
