### ISSUE TITLE
I can't open dancer.

### ISSUE THREAD

**Issue by deku12332** [Wieku/danser-go#34]
When I try to open it the tab opens for a sec and then closes. can someone help me?

**Comment by Wieku** [comment]
Read the README file...

**Comment by deku12332** [comment]
There is no readme file

**Comment by Wieku** [comment]
...

**Comment by deku12332** [comment]
![Screenshot (101)](https://user-images.githubusercontent.com/70452428/91646502-10781100-ea0d-11ea-9cb3-85a770e89db1.png)
