### ISSUE TITLE
Can't open danser on ubuntu server 20.04.6. version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by kolesto65** [Wieku/danser-go#345]
When I'm trying to launch danser, this is what I'm getting:

./danser-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./danser-cli)

./danser-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/kolesto65/danser/libdanser-core.so)

./danser-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/kolesto65/danser/libdanser-core.so)

./danser-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/kolesto65/danser/libdanser-core.so)

Problem is with both danser and danser-cli.

Hardware:
Intel Xeon E5 2678v3 x2
Nvidia CMP 40 HX

**Comment by Wieku** [comment]
Your linux install is too old. What's distro/kernel version do you have now?

**Comment by kolesto65** [comment]
> Your linux install is too old. What's distro/kernel version do you have now?

Ubuntu 20.04.6 LTS
5.4.0-163-generic

**Comment by kolesto65** [comment]
Just updated kernel to 6.5.5-060505-generic, didn't fixed the issue. Should I update my distro?

**Comment by Wieku** [comment]
iirc ubuntu 22 is required, I will see if it's possible to lower the requirement with the next release

**Comment by kolesto65** [comment]
Updating to ubuntu 22 really fixed the issue. Thanks🙂
