### ISSUE TITLE
broken / unresponsive danser

### ISSUE THREAD

**Issue by EvyGithub** [Wieku/danser-go#346]
danser (client window) opens, but I can only hover on the buttons (except "danse!") at most

**video recording:**

https://github.com/Wieku/danser-go/assets/110493699/b26ead2c-9d9f-42d5-83bb-05f14bf98078

**log**
[Edanser2danser.exe.txt](https://github.com/Wieku/danser-go/files/13059910/Edanser2danser.exe.txt)

**computer**
Operating System: Windows 11
CPU: 11th gen inten core 15-1135G7 @ 2.40GHz  2.42 GHz
GPU: intel Iris Xe graphics

also the last line is always checking github, and when I close the client window, the terminal doesn't close
and is `danser-cli.exe` supposed to rickroll you and do nothing else

I did have this problem before

**Comment by Someone2124** [comment]
did you choose the map and diff then where it say "watch" did you press record?

**Comment by NotJansel** [comment]
To the buttons: that is expected behaviour, since you have no replay or map etc selected as the "danse!" button would start ffmpeg with no arguments, resulting in nothing. To the second thing where `danser-cli.exe`  rickrolls you, it's expected from it when you don't pass any arguments.

**Comment by EvyGithub** [comment]
Isn't the "danse" button supposed to be a little brighter when you hover over it?

**Comment by Wieku** [comment]
@EvyGithub if you can click it (which means you have to pick a map or replay(s)), then yes.
