### ISSUE TITLE
Danser don't launch

### ISSUE THREAD

**Issue by i-yitsure** [Wieku/danser-go#348]
That a day that always making videos when on certain moment trying to launch on Powershell from the folder of Danser and Danser-client writing the command  `/.danser -md5 0` appear on my screen the issue related to a incorrect value and failure of certain routines, not only happen in Powershell also happen on CMD

![image](https://github.com/Wieku/danser-go/assets/28587232/679cbb08-5ac8-44ee-a5c3-7b593c504a68)

![image](https://github.com/Wieku/danser-go/assets/28587232/32be2d3f-07a0-4029-ad21-a6ed0c5396f3)

[danser.log](https://github.com/Wieku/danser-go/files/13532492/danser.log)

**Computer configuration:**
Operating System: Windows 10
AMD A8-7410 APU with AMD Radeon R5 Graphics
GPU: AMD Radeon(TM) R5 Graphics
Sound Card: Realtek High Definition Audio

**Comment by Wieku** [comment]
1. Why are you running danser launcher through cli?
2. Why are you manually modifying launcher settings with empty characters?

**Comment by i-yitsure** [comment]
> 1. Why are you running danser launcher through cli?
> 2. Why are you manually modifying launcher settings with empty characters?

Large explaination:
No, i always launch the client using the powershell the the command but for some reason this mark like a error that was shown on the images (i changed to CMD is because to find a alternative)

Answer for the questions
1- no, again i ran on the powershell
2- i dont know, i never touch the parameters, only i wrote the command, i dont know how affect to the lauch
