### ISSUE TITLE
Feature request: toggle to start render from first note not from 00:00

### ISSUE THREAD

**Issue by takoine** [Wieku/danser-go#354]
As the title suggests, there's a issue with the logic how long or from where the video should start with maps that aren't "in one piece". Maps that are cut and rendered via Danser are treated as full long maps so it start's from 0 each time even though first note can be 2 minutes in.

**Comment by Infiniti727** [comment]
Theres already an option to skip the intro inside the "Time/offset" settings.
![imagen](https://github.com/Wieku/danser-go/assets/45731253/c8b08253-c3d4-4fce-b8ed-02e9cb210e08)
