### ISSUE TITLE
Fix this please

### ISSUE THREAD

**Issue by MijunElMacho21** [Wieku/danser-go#360]
i have a problem with danser, help me fix this
![Screenshot_149](https://github.com/Wieku/danser-go/assets/132280765/ee1a5d0d-46a2-42a5-9d86-1812977ad972)
there is an opengl error on my laptop

here is my laptop information if you want to know:
processor: Intel Core I3
graphics card: Intel HD Graphics 3000

pls help me fix that
@Wieku

**Comment by Wieku** [comment]
Laptop too old
