### ISSUE TITLE
Crash while viewing VS mode knockout

### ISSUE THREAD

**Issue by Slingexe** [Wieku/danser-go#361]
**Describe the bug**
I was watching a knockout with 15 replays and danser on VS mode, when about half way though it freezes and when I close danser I got an error "panic: send on closed channel" then I tried again and it didn't even launch

**Screenshots**

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/15143072/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: AMD Ryzen 7 1700X Eight-Core Processor, 16 cores
GPU: NVIDIA GeForce RTX 2080 Ti

**Comment by benilyasss** [comment]
wieku too lazy for fix the problem frfr

**Comment by Wieku** [comment]
@benilyasss I have life, you know? I'm fed up.

**Comment by Wieku** [comment]
@Slingexe sorry for replying this late, in "Hide mods" option don't use additional characters (you have `+AT`), just `AT`, or for example `NFATHR` should work.

**Comment by Slingexe** [comment]
> wieku too lazy for fix the problem frfr

Not cool

**Comment by Slingexe** [comment]
> @Slingexe sorry for replying this late, in "Hide mods" option don't use additional characters (you have `+AT`), just `AT`, or for example `NFATHR` should work.

Alright thanks
