### ISSUE TITLE
Consider rewriting danser in C# and using existing osu!lazer code

### ISSUE THREAD

**Issue by developomp** [Wieku/danser-go#363]
With (partial) lazer mod support being [planned](https://github.com/Wieku/danser-go/issues/274#issuecomment-1220621016) to happen eventually, this is a good time to consider whether rewriting new lazer mods in Go is a better solution than rewriting danser to be based on lazer's code (like [`ppy/osu-tools`](https://github.com/ppy/osu-tools/blob/master/PerformanceCalculator/PerformanceCalculator.csproj), for example).

**Comment by Wieku** [comment]
Probably won't happen. Danser is a pet project to explore osu's mechanics and learn. Relying on osu's base won't be fun.
