### ISSUE TITLE
i cannot open the danser

### ISSUE THREAD

**Issue by Hduc5** [Wieku/danser-go#365]
i opened the danser.exe then this showing up

![aaa](https://github.com/Wieku/danser-go/assets/173800760/2974a9d8-eb6e-40cc-8e01-799ad2b9f720)

My laptop is intel i5-4200
1.6ghz, 4gb ram
Window 10 Pro, Winlibs x86 mingw64
Go1 1.22.4  vers

Thanks for helping me

**Comment by Wieku** [comment]
It means you miss assets in the folder you're running danser from.

> intel i5-4200, 1.6ghz, 4gb ram

Unless you have a dedicated GPU (NVIDIA, AMD), that laptop is way too old to run danser.
