### ISSUE TITLE
need help with compiling (ARM64, have drivers for high potentially OpenGL levels in a PROOT container, using mesa.)

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [Wieku/danser-go#367]
The drivers i have access to: LLVMpipe, zink(cpu conditional), virpipe(slow for me, removes the mesa needed for zink)
the gpu i have: Mali G52, so no turnip drivers. (its a phone btw)
box64 doesnt work(tested with release zips) and compiling gives these errors:

root@localhost:~/danser-go# go build
# github.com/inkyblackness/imgui-go/v4
In file included from /usr/include/string.h:548,
                 from ../go/pkg/mod/github.com/neclepsio/imgui-go/v4@v4.0.0-20220215070259-092710ff7bb1/imgui/imgui.h:63,
                 from wrapper/ConfiguredImGui.h:7,
                 from wrapper.cpp:1:
In function ‘void* memset(void*, int, size_t)’,
    inlined from ‘void ImFontAtlasBuildPackCustomRects(ImFontAtlas*, void*)’ at ../go/pkg/mod/github.com/neclepsio/imgui-go/v4@v4.0.0-20220215070259-092710ff7bb1/imgui/imgui_draw.cpp:2630:11:
/usr/include/aarch64-linux-gnu/bits/string_fortified.h:59:33: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/wieku/danser-go
/usr/lib/go-1.22/pkg/tool/linux_arm64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lXxf86vm: No such file or directory
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbass.so when searching for -lbass
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbass.so when searching for -lbass
/usr/bin/ld: cannot find -lbass: No such file or directory
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbass.so when searching for -lbass
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbass.so when searching for -lbass
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: cannot find -lbass_fx: No such file or directory
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbassmix.so when searching for -lbassmix
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbassmix.so when searching for -lbassmix
/usr/bin/ld: cannot find -lbassmix: No such file or directory
/usr/bin/ld: skipping incompatible /root/danser-go/framework/bass/../..//libbassmix.so when searching for -lbassmix
/usr/bin/ld: skipping incompatible /root/danser-go/framework/util/pixconv/../../..//libbassmix.so when searching for -lbassmix
collect2: error: ld returned 1 exit status

root@localhost:~/danser-go#

CPU ghz: (8) 2.002 GHz
Bash 5.2.21
3701 Allocated ram for apps, idling at 2619 MB with other apps open.
Phone: SM-217F
mounting is barely possible but no fuse modules or other kernel stuff modules so i am stuck with fakeroot and fake sudo but a mostly real rootfs.

**Comment by khang06** [comment]
you need to replace the bass/bassfx/bassmix shared libraries with the proper arm64 versions

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> you need to replace the bass/bassfx/bassmix shared libraries with the proper arm64 versions

Thanks, ill update with a comment if it worked or i couldnt find the arm64 ones in packages, thanks for the help!
