### ISSUE TITLE
gpu underutilized and slow processing

### ISSUE THREAD

**Issue by Lukagritl** [Wieku/danser-go#371]
![image](https://github.com/user-attachments/assets/b3a6c0f7-1521-48c6-8d2a-c772275ebde6)
the selected encoder is h265 hvenc hardware
**Computer configuration:**
Operating System: Windows 11
CPU: ryzen 5700x
GPU: RTX4070S
![image](https://github.com/user-attachments/assets/f38b2271-d018-4365-9ec3-10397f39fb8f)
its constantly running between 14 and 17%

**Comment by Wieku** [comment]
How is over 5x real time slow processing??? Encoder on your GPU can't encode faster.

Also I don't undestand why underutilization is an issue? I think it's good to be able to do other stuff while videos are being rendered. I should add an artificial gpu gobbler?
