### ISSUE TITLE
Lazer replays are now completely broken

### ISSUE THREAD

**Issue by aL1NaZ4R** [Wieku/danser-go#374]
**Describe the bug**
Using a lazer replay in danser, will only display the hit objects. Cursor is pinned and not moving. There's no clicks.

**Screenshots**
https://link.issou.best/si6TN0
https://link.issou.best/eX1RKH

**Logs**
I used o!rdr. If it's neccesary, then ask me to do one locally.

**Comment by Wieku** [comment]
Lazer replays are not supported currently.

Can you share the replay files?

**Comment by aL1NaZ4R** [comment]
Sure, here it is:
[solo-replay-osu_3438235_3494518065.txt](https://github.com/user-attachments/files/16949640/solo-replay-osu_3438235_3494518065.txt)
(Rename the extension to .osr)

**Comment by Wieku** [comment]
Please don't report issues with edited replays. Did you expect a cut replay to the last 10 seconds to work properly?
The same replay breaks in lazer... Please check if it works in lazer before reporting...

**Comment by aL1NaZ4R** [comment]
Wait... It's cut???!!
Bro I've downloaded it directly from osu website. There's no way that it's cut

**Comment by Wieku** [comment]
Then I think it's worth reporting here https://github.com/ppy/osu-web

Replay info
![image](https://github.com/user-attachments/assets/9f95bcda-f944-4895-a143-03fb98a84674)

**Comment by aL1NaZ4R** [comment]
Ah, I see. Got it 👍
