### ISSUE TITLE
Danser does not open.

### ISSUE THREAD

**Issue by Lev1nho-x** [Wieku/danser-go#389]
"Danser isn't opening"
In the very short... Danser isn't opening.

Screenshots...
N/A.

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Tiny11
CPU: Intel Pentium D 925
GPU: NVIDIA GeForce GT 1030 (idk if its a graphic issue or no :).)

**Comment by NotJansel** [comment]
it s a cpu issue most likely.

**Comment by Wieku** [comment]
It would be good to not ignore the log file request...

**Comment by Lev1nho-x** [comment]
> It would be good to not ignore the log file request...



> it's a cpu issue most likely, its too old

Sorry for the late check at the issue i've listed, And no it is not a CPU issue because it was running nicely back in the day, But before 2 months or something after reinstalling Windows i get issues running danser even i tried different operating system (tiny11, tiny10, win10, win11) and still nothing change.

And by the way i am currently using tiny11, When i open danser it just opens an empty console for few seconds then closes it, And when i retry doing that it sometimes open a console that has some stuff in it but i can't catch them because it closes so fast, When i used Windows 10 even that console wasn't here, Clicking danser.exe that time was just like clicking the air.

Oh, Nevermind i caught it,
![image](https://github.com/user-attachments/assets/aeb08525-6179-4bce-98db-51c293b3f993)

And another "by the way", I have tried a bit older versions of danser and yeah, nothing special changed just clicking air :D

Hope this information be useful to you, And again sorry for late reply i just thought there is no hope to see an answer here XD

And thanks.
