### ISSUE TITLE
Add List imported songs

### ISSUE THREAD

**Issue by GamingInfinite** [Wieku/danser-go#39]
I always find myself going back into osu in order to get the names of the songs and difficulties.  A command like danser-***.exe -list would make it a whole lot easier to utilize this tool.

**Comment by Wieku** [comment]
This is partially fixed by #36 but an option to show results for partial parameters would be cool

**Comment by GamingInfinite** [comment]
Wait, I finally read the most recent patch notes, can you add something in the wiki or something on how to add aliases for beatmaps?

**Comment by Wieku** [comment]
Will be superseded by GUI in the future
