### ISSUE TITLE
Doesn't handle apostrophies?

### ISSUE THREAD

**Issue by GamingInfinite** [Wieku/danser-go#40]
Most songs I've run into that have an apostrophe in either the title or difficulty are just impossible to get to run.  It always comes back with a beat map not found even though I've copy and pasted the name directly into the tag.  Weird bug, and because I have no idea how go works I have no idea how hard of a bug it is to fix.

**Comment by Wieku** [comment]
This is a basic knowledge of using a command line, not a bug. You need to escape it, for example:
`"Some name with \"apostrophes\""`
