### ISSUE TITLE
nice update

### ISSUE THREAD

**Issue by asdfqwerty0123** [Wieku/danser-go#43]
Thanks for your hard work. I've been waiting for this so much!

**Comment by Wieku** [comment]
Just why. GitHub is not a place for this

**Comment by asdfqwerty0123** [comment]
I know but I just wanted to tell you that this fork of osu is amazing lol
Anyway, I'm sorry, and have a good day

**Comment by Wieku** [comment]
This is not a fork of osu

**Comment by asdfqwerty0123** [comment]
Sorry again, I mean danser
