### ISSUE TITLE
Relax replay

### ISSUE THREAD

**Issue by SpookyBear0** [Wieku/danser-go#45]
Replays in relax do not work as danser needs to see a keypress, I think it would be nice to have a check for relax and make it behave like relax.

**Comment by SpookyBear0** [comment]
Fixed in latest commit

**Comment by Ning1253** [comment]
This should probably be reopened as relax replays do not seem to play perfectly, playing differently from how they do in the main game (I got a slider break on a map which appeared and played SS in relax in the main game...)

**Comment by Wieku** [comment]
I think that replay would be nice...
