### ISSUE TITLE
Trouble with error: No beatmap specified, closing...

### ISSUE THREAD

**Issue by NeoMaster831** [Wieku/danser-go#48]
Hello sir, I like your project and I wanted to run this but... there's problem:
> No beatmap specified, closing...

I think there's no problem. Here are pictures:
![a](https://user-images.githubusercontent.com/72684393/99795280-d7b08980-2b6e-11eb-918b-bb9ced4c1b7c.png)

![ad](https://user-images.githubusercontent.com/72684393/99795445-278f5080-2b6f-11eb-802c-619fb3f2deb9.png)

![da](https://user-images.githubusercontent.com/72684393/99795505-3e35a780-2b6f-11eb-8ca3-8c5c81faacf6.png)

![d](https://user-images.githubusercontent.com/72684393/99795584-56a5c200-2b6f-11eb-9199-1611ef628e5b.png)

**Comment by Wieku** [comment]
Run with `./danser-0.4.1b`, it seems that running with wildcard adds log file path to arguments which it seems to break argument parser

**Comment by NeoMaster831** [comment]
It worked, thank you!
