### ISSUE TITLE
knockout mode issue?

### ISSUE THREAD

**Issue by NeoMaster831** [Wieku/danser-go#49]
Hello, and sorry for opening new issue. Is it issue or something?
if it is not, then how to display knockout mode like you: https://www.youtube.com/watch?v=8Lz2ABkKTLc

I typed like this,
![s](https://user-images.githubusercontent.com/72684393/99799040-5dcfce80-2b75-11eb-8331-f677634784c3.png)

and it plays solo.
![a](https://user-images.githubusercontent.com/72684393/99799126-7fc95100-2b75-11eb-8c21-2252009bd9b8.png)

**Comment by Wieku** [comment]
https://github.com/Wieku/danser-go/wiki/Knockout

With no matching replays danser as a replay is displayed.
