### ISSUE TITLE
GUI song select

### ISSUE THREAD

**Issue by GamingInfinite** [Wieku/danser-go#51]
Osu-like GUI for selecting which beatmap to do (each of which would essentially run an auto-generated command-line for each of said beatmaps).

**Comment by GamingInfinite** [comment]
nvm #13

**Comment by Mempler** [comment]
Hey there 👋 just want to notify you that a GUI is actually in the works right now 🎉 
Wieku has send some pictures and videos in the [Danser discord](https://discord.com/invite/UTPvbe8).

**Comment by GamingInfinite** [comment]
oh really?  in #13 he said he wouldn't add it but alright
