### ISSUE TITLE
(MAC) danser-go will open with no window, and then close.

### ISSUE THREAD

**Issue by 1tsJustR0n** [Wieku/danser-go#52]
<img width="584" alt="Screen Shot 2020-12-01 at 2 28 39 PM" src="https://user-images.githubusercontent.com/60608663/100787383-8e1f3480-33e1-11eb-967f-638067866d65.png">

**Comment by Wieku** [comment]
Danser won't work with MacOS. Use Windows/Linux on dualboot.

I should update the readme, sorry.

**Comment by lapcatlak** [comment]
i need it for mac.
