### ISSUE TITLE
flag provided but not defined: -mover

### ISSUE THREAD

**Issue by CenturaPVP** [Wieku/danser-go#53]
The console said the string -mover is provided but not defined, even though I put the "linear" after the =
![image](https://user-images.githubusercontent.com/66526922/101206812-4d1f5e00-3635-11eb-960c-90c3d849d229.png)

**Logs**
2020/12/04 13:33:11 Ran using: [danser-0.4.1b.exe -t=Verflucht -d=fanzhen's One More Extra -cursors=16 -tag=1 -speed=1 -pitch=1 -mover=linear -knockout]

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8750h
GPU: GTX1060 (if it's a graphics issue)
Sound Card: no idea (if it's a sound issue)

**Comment by MasterZitron** [comment]
Change movers in settings

**Comment by CenturaPVP** [comment]
what do i change?
