### ISSUE TITLE
runtime error: index out of range [41] with length 3

### ISSUE THREAD

**Issue by MasterIO02** [Wieku/danser-go#55]
**Describe the bug**
Tried to load "859515 K A Z M A S A - Bon Appetit S (Oldskool HappyHardcore Remix) (Short Ver)", resulting in this error right before the first note has been hit by danser or a replay.
Loading another map works fine with danser and replays but not this one. 
Every difficulty of the map results in the same error.
I tried to : reset DB like said in other issues, reset config, renaming audio file (because it has a ",").
Same problem with both Linux (Pop OS) and Windows 10
No success.

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/5665914/danser.log)
[danser.db.txt](https://github.com/Wieku/danser-go/files/5665915/danser.db.txt)
(renamed danser.db to danser.db.txt since github doesn't recognize .db files)

**Computer configuration:**
Operating System: Pop! OS 20.04/ Windows 10 1809
CPU: Intel i5 6500
GPU: GTX1050Ti

**Comment by Wieku** [comment]
Can you send map link or zipped folder of it here?
Did you have map hitsounds on?

**Comment by MasterIO02** [comment]
Here is the map : https://osu.ppy.sh/beatmapsets/859515#osu/2082013
I tried disabling hitsounds just now (I haven't seen any clear option on settings.json, so I just set SampleVolume to 0 and HitsoundPositionMultiplied to 0, and IgnoreBeatmapSamples to true) and the same problem occurs.

Also, I was about to create a new issue for another problem I faced, but after more search I found out that when danser is run as root on Linux, it won't open if OBS is running (failed to run BASS error 3). Running danser as a regular user works when OBS is open. Maybe you could add this in the wiki or readme in case someone face this problem? I haven't tried with administrator on Windows.
