### ISSUE TITLE
Long loading times when having many beatmaps

### ISSUE THREAD

**Issue by MinisBett** [Wieku/danser-go#57]
I have 60k+ beatmaps and it takes a long time to import all beatmaps.

Is there room for improvement?

![image](https://user-images.githubusercontent.com/39670899/101910096-c4696a80-3bbe-11eb-9fc0-6ca875aea353.png)

**Comment by Wieku** [comment]
> I have 60k+ beatmaps
This is your answer. Just wait for danser to cache them

**Comment by MinisBett** [comment]
Do they get imported only once? Or does it import all beatmaps everytime you start it?

**Comment by Wieku** [comment]
Yes, only once.
