### ISSUE TITLE
Need help on starting up the App

### ISSUE THREAD

**Issue by Copqer** [Wieku/danser-go#59]
I didnt find the explanation clear, whenever i try to launch the app it starts up cmd and then closes, the danser logs say "didnt specify a beatmap" and there is no explanation on how to specify a beatmap? even if i try to play some random map on fullscreen / non-fullscreen it doesnt specify anything

**Comment by Wieku** [comment]
> I didnt find the explanation clear
Hmm, hmm, hmm.
https://github.com/Wieku/danser-go#how-to-run-it

Learn how to read, please.

**Comment by Copqer** [comment]
what the hell is a repository though

**Comment by Copqer** [comment]
i legitimately have 0 idea on programming / github terms
