### ISSUE TITLE
unable to see names and combo in knockout

### ISSUE THREAD

**Issue by imdoingthisfortheprofile** [Wieku/danser-go#62]
when using knockout, everything works (colors, all cursors, etc) but i am unable to see the names or combo.
![image](https://user-images.githubusercontent.com/54502653/102602987-23c4fe80-411a-11eb-870d-9f56d9ee3a02.png)
why is this and is there nay way to fix it?

**Comment by Wieku** [comment]
It's hard to tell, can you send me `settings.json` and `danser.log`? Best would be a one frame capture using [RenderDoc](https://renderdoc.org/)

**Comment by imdoingthisfortheprofile** [comment]
danser.log https://pastebin.com/PXMireqN
settings.json https://pastebin.com/9PvJy7Uu

**Comment by imdoingthisfortheprofile** [comment]
[frame.zip](https://github.com/Wieku/danser-go/files/5715915/frame.zip)

**Comment by Wieku** [comment]
Looks like a driver bug
