### ISSUE TITLE
Danser goes offscreen and doesn't click circles sometimes. (mostly in aspire maps)

### ISSUE THREAD

**Issue by Condukt** [Wieku/danser-go#64]
**Describe the bug**
Danser sometimes goes off screen and doesnt click circles or sliders. I've seen this most happening in Aspire/2B maps. Below is a youtube video showing this happening in XNOR XNOR XNOR. (sorry if i dont know what im doing i just made this account to report this lol.)

**Video**
https://www.youtube.com/watch?v=kKD-Hm1QySQ
is there a way to fix this?

**Computer configuration:**
Operating System: Windows 10
CPU: Ryzen 5 3600
GPU: GTX 1060 6GB (if it's a graphics issue(probably not lol))

**Comment by Condukt** [comment]
also logs and settings: 
[logs.txt](https://github.com/Wieku/danser-go/files/5760801/logs.txt)
[settings.txt](https://github.com/Wieku/danser-go/files/5760804/settings.txt)

**Comment by hyperdefined** [comment]
Change `BounceOnEdges` from `false` to `true`. It won't go off screen if this is on.

**Comment by Condukt** [comment]
Setting BounceOnEdges to true doesn't help. It will just refuse to click circles, but this time, bounce off the edges.

**Comment by Hanoji-jp** [comment]
2bsliderdance true!!!

**Comment by Condukt** [comment]
I'm a dumbass. I figured it out myself.

**Comment by Wieku** [comment]
?
