### ISSUE TITLE
songs that don't work with danser

### ISSUE THREAD

**Issue by LilStardust** [Wieku/danser-go#65]
I have a problem with the following maps:
map #1
https://osu.ppy.sh/beatmapsets/825993#osu/1740463

Danser cannot find this map at all even though the location of the song file is correct. Danser just gives the reply of not being able to locate the map.

map#2
https://osu.ppy.sh/beatmapsets/73474#osu/209576

this one is a bit weird. with this map danser is able to locate the song but not the storyboard and player it normally, however, when I try to use the knockout feature to watch my replays it cant locate the replays and then shows danser playing.

every other song ive used seems to work except these 2.

**Comment by Wieku** [comment]
Most probably PEBKAC.
No danser.log, even if it's requested in template. No settings.json. no eventual screenshots.
Closing for not enough info provided

**Comment by M3IY0U** [comment]
While this issue might be already closed, you can still join [the discord server](https://discord.gg/UTPvbe8) and ask this in the helpdesk channel. Should be easier to send screenshots etc there as well :)
