### ISSUE TITLE
songs that don't work with danser

### ISSUE THREAD

**Issue by LilStardust** [Wieku/danser-go#66]
DISCLAIMER:
I'm really bad at coding and this is my first time discussing an issue with a developer. 

**Describe the bug**
There are 2 beatmaps that I have found to not work with danser. I have not had any issues playing any other map (with or without -knockout) before.

Map #1 
https://osu.ppy.sh/beatmapsets/825993#osu/1740463

with this beatmap danser is unable to find the beatmap even with using different variants of the title.

Map #2 
https://osu.ppy.sh/beatmapsets/73474#osu/209576

Danser can find the song but then says it cant locate the storyboard and danser begins to play normally. When I try to play this song using -knockout with my replays it cannot find the replay and starts playing danser normally (also without the storyboard)

**Screenshots**

When I try to run beatmap #2 with -knockout

https://www.youtube.com/watch?v=aWGcfWJCd2g&feature=youtu.be&ab_channel=LilStardust

**Logs**
Put danser.log here.

Log for beatmap #1:

https://pastebin.com/Vijrdqa5

Log for beatmap #2:

https://pastebin.com/W5Mkd3iU

log for beatmap 2 with -knockout:

https://pastebin.com/vTCQvyip

my settings.JSON

https://pastebin.com/czk4DYRS

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 7700K
GPU: GTX1060ti 6GB

**Comment by Condukt** [comment]
the aspire map ping im pretty sure also doesnt work with danser

**Comment by Wieku** [comment]
> the aspire map ping im pretty sure also doesnt work with danser

This issue is not about aspire maps.

**Comment by oofyXD** [comment]
try melonis45's danser menu. search it up on the menu and see if it works, if it does not work, its a big
