### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by IllianDeCube09** [Wieku/danser-go#68]
**Describe the bug**
I don't know what the problem is, but all I have are incomprehensible strings in CMD and the same strings in danser.log. Just a couple of minutes before that, I launched the same level and everything worked fine (trying different settings). Now any levels do not work, giving the same error in CMD.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/68920871/104188849-eb6bc400-542a-11eb-920d-8549c6236369.png)

**Logs**
2021/01/11 16:17:13 Ran using: [danser-0.4.1b.exe -a=Seven Lions -t=December]
2021/01/11 16:17:13 panic: invalid character '\n' in string literal
2021/01/11 16:17:13 goroutine 1 [running, locked to thread]:
2021/01/11 16:17:13 github.com/wieku/danser-go/app/settings.load(0xc0000060e8, 0x10fa500, 0xc00003a4e0)
2021/01/11 16:17:13 	C:/Users/Wieku/go/src/github.com/wieku/danser-go/app/settings/manager.go:54 +0xb4
2021/01/11 16:17:13 github.com/wieku/danser-go/app/settings.LoadSettings(0x0, 0x0, 0x0)
2021/01/11 16:17:13 	C:/Users/Wieku/go/src/github.com/wieku/danser-go/app/settings/manager.go:44 +0x2b0
2021/01/11 16:17:13 main.run.func1()
2021/01/11 16:17:13 	C:/Users/Wieku/go/src/github.com/wieku/danser-go/main.go:106 +0x8d4
2021/01/11 16:17:13 github.com/faiface/mainthread.Call.func1()
2021/01/11 16:17:13 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x36
2021/01/11 16:17:13 github.com/faiface/mainthread.Run(0x11aa600)
2021/01/11 16:17:13 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc6
2021/01/11 16:17:13 main.main()
2021/01/11 16:17:13 	C:/Users/Wieku/go/src/github.com/wieku/danser-go/main.go:422 +0x1c5
2021/01/11 16:17:13 
2021/01/11 16:17:13 goroutine 6 [chan receive]:
2021/01/11 16:17:13 github.com/faiface/mainthread.Call(0xc000004be0)
2021/01/11 16:17:13 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xca
2021/01/11 16:17:13 main.run()
2021/01/11 16:17:13 	C:/Users/Wieku/go/src/github.com/wieku/danser-go/main.go:56 +0xa5
2021/01/11 16:17:13 github.com/faiface/mainthread.Run.func1(0x11aa600, 0xc00014c060)
2021/01/11 16:17:13 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x2e
2021/01/11 16:17:13 created by github.com/faiface/mainthread.Run
2021/01/11 16:17:13 	C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xba
2021/01/11 16:17:13 

**Computer configuration:**
Operating System: Windows 10 pro
CPU: Intel(R) Core(TM) i5-5200U 2.20GHz

**Comment by Wieku** [comment]
Can you send your settings file? Error states that (most probably) path is broken.

**Comment by IllianDeCube09** [comment]
{
	"General": {
		"OsuSongsDir": "C:\\Users\\ASUS\\AppData\\Local\\osu!\\Songs",
		"OsuSkinsDir": "C:\\Users\\ASUS\\AppData\\Local\\osu!\\Skins",
		"DiscordPresenceOn": false
	},
	"Graphics": {
		"Width": 1366,
		"Height": 768,
		"WindowWidth": 1024,
		"WindowHeight": 576,
		"Fullscreen": true,
		"VSync": true,
		"FPSCap": 0,
		"MSAA": 0,
		"ShowFPS": false
	},
	"Audio": {
		"GeneralVolume": 0.1,
		"MusicVolume": 0.5,
		"SampleVolume": 0.5,
		"Offset": 0,
		"HitsoundPositionMultiplier": 1,
		"IgnoreBeatmapSamples": false,
		"IgnoreBeatmapSampleVolume": false,
		"BeatScale": 1.2,
		"BeatUseTimingPoints": false,
		"Linux/Unix": {
			"BassPlaybackBufferLength": 100,
			"BassDeviceBufferLength": 10,
			"BassUpdatePeriod": 5
		}
	},
	"Input": {
		"LeftKey": "Z",
		"RightKey": "X",
		"MouseButtonsDisabled": true
	},
	"Gameplay": {
		"ShowHitErrorMeter": true,
		"HitErrorMeterOpacity": 1,
		"HitErrorMeterScale": 1,
		"ShowScore": false,
		"ScoreScale": 1,
		"ScoreOpacity": 1,
		"ShowCombo": false,
		"ComboScale": 1,
		"ComboOpacity": 1,
		"ShowKeyOverlay": true,
		"KeyOverlayScale": 1,
		"KeyOverlayOpacity": 1,
		"ProgressBar": "Pie",
		"Boundaries": {
			"Enabled": true,
			"BorderThickness": 1,
			"BorderFill": 1,
			"BorderColor": {
				"Hue": 0,
				"Saturation": 0,
				"Value": 1
			},
			"BorderOpacity": 1,
			"BackgroundColor": {
				"Hue": 0,
				"Saturation": 1,
				"Value": 0
			},
			"BackgroundOpacity": 0.5
		}
	},
	"Skin": {
		"CurrentSkin": "E.CS r20200326 [HD],
		"UseColorsFromSkin": true
	},
	"Cursor": {
		"TrailStyle": 1,
		"Style23Speed": 0.18,
		"Style4Shift": 0.5,
		"Colors": {
			"EnableRainbow": false,
			"RainbowSpeed": 8,
			"BaseColor": {
				"Hue": 0,
				"Saturation": 0,
				"Value": 1
			},
			"EnableCustomHueOffset": false,
			"HueOffset": 0,
			"FlashToTheBeat": false,
			"FlashAmplitude": 0
		},
		"EnableCustomTagColorOffset": true,
		"TagColorOffset": -72,
		"EnableTrailGlow": false,
		"EnableCustomTrailGlowOffset": true,
		"TrailGlowOffset": -36,
		"ScaleToCS": false,
		"CursorSize": 12,
		"CursorExpand": false,
		"ScaleToTheBeat": false,
		"ShowCursorsOnBreaks": true,
		"BounceOnEdges": true,
		"TrailScale": 1,
		"TrailEndScale": 0.5,
		"TrailDensity": 1,
		"TrailMaxLength": 2000,
		"TrailRemoveSpeed": 0.75,
		"GlowEndScale": 0.4,
		"InnerLengthMult": 0.9,
		"AdditiveBlending": true
	},
	"Objects": {
		"DrawApproachCircles": true,
		"DrawComboNumbers": true,
		"DrawFollowPoints": true,
		"LoadSpinners": true,
		"ScaleToTheBeat": false,
		"StackEnabled": true,
		"Sliders": {
			"ForceSliderBallTexture": true,
			"DrawEndCircles": false,
			"DrawSliderFollowCircle": true,
			"DrawScorePoints": true,
			"SliderMerge": false,
			"SliderDistortions": true,
			"BorderWidth": 1,
			"Quality": {
				"CircleLevelOfDetail": 50,
				"PathLevelOfDetail": 50
			},
			"Snaking": {
				"In": true,
				"Out": true,
				"DurationMultiplier": 0,
				"FadeMultiplier": 0
			}
		},
		"Colors": {
			"MandalaTexturesTrigger": 5,
			"MandalaTexturesAlpha": 0.3,
			"Color": {
				"EnableRainbow": false,
				"RainbowSpeed": 8,
				"BaseColor": {
					"Hue": 0,
					"Saturation": 1,
					"Value": 1
				},
				"EnableCustomHueOffset": false,
				"HueOffset": 0,
				"FlashToTheBeat": false,
				"FlashAmplitude": 100
			},
			"UseComboColors": true,
			"ComboColors": [
				{
					"Hue": 0,
					"Saturation": 0,
					"Value": 1
				}
			],
			"Sliders": {
				"WhiteScorePoints": true,
				"ScorePointColorOffset": 0,
				"SliderBallTint": false,
				"Border": {
					"UseHitCircleColor": false,
					"Color": {
						"EnableRainbow": false,
						"RainbowSpeed": 8,
						"BaseColor": {
							"Hue": 0,
							"Saturation": 0,
							"Value": 1
						},
						"EnableCustomHueOffset": false,
						"HueOffset": 0,
						"FlashToTheBeat": false,
						"FlashAmplitude": 100
					},
					"EnableCustomGradientOffset": true,
					"CustomGradientOffset": 0
				},
				"Body": {
					"UseHitCircleColor": false,
					"Color": {
						"EnableRainbow": false,
						"RainbowSpeed": 0,
						"BaseColor": {
							"Hue": 0,
							"Saturation": 0,
							"Value": 1
						},
						"EnableCustomHueOffset": false,
						"HueOffset": 0,
						"FlashToTheBeat": true,
						"FlashAmplitude": 100
					},
					"InnerOffset": -0.5,
					"OuterOffset": -0.05,
					"InnerAlpha": 0.1,
					"OuterAlpha": 0.1
				}
			}
		}
	},
	"Playfield": {
		"DrawObjects": true,
		"DrawCursors": true,
		"Scale": 1,
		"OsuShift": false,
		"ShiftY": 0,
		"ShiftX": 0,
		"ScaleStoryboardWithPlayfield": false,
		"LeadInTime": 5,
		"LeadInHold": 2,
		"FadeOutTime": 5,
		"SeizureWarning": {
			"Enabled": false,
			"Duration": 5
		},
		"Background": {
			"LoadStoryboards": true,
			"FlashToTheBeat": false,
			"Dim": {
				"Intro": 0,
				"Normal": 0.95,
				"Breaks": 0.5
			},
			"Parallax": {
				"Amount": 0.01,
				"Speed": 0.5
			},
			"Blur": {
				"Enabled": false,
				"Values": {
					"Intro": 0,
					"Normal": 0.6,
					"Breaks": 0.3
				}
			},
			"Triangles": {
				"Enabled": false,
				"Shadowed": true,
				"DrawOverBlur": true,
				"ParallaxMultiplier": 0.5
			}
		},
		"Logo": {
			"DrawSpectrum": true,
			"Dim": {
				"Intro": 0,
				"Normal": 1,
				"Breaks": 1
			}
		},
		"Bloom": {
			"Enabled": true,
			"BloomToTheBeat": true,
			"BloomBeatAddition": 0.3,
			"Threshold": 0.8,
			"Blur": 0.6,
			"Power": 0.7
		}
	},
	"Dance": {
		"Movers": [
			"spline"
		],
		"Spinners": [
			"circle"
		],
		"DoSpinnersTogether": true,
		"SpinnerRadius": 100,
		"Battle": false,
		"SliderDance": false,
		"RandomSliderDance": false,
		"TAGSliderDance": false,
		"SliderDance2B": true,
		"Bezier": {
			"Aggressiveness": 60,
			"SliderAggressiveness": 3
		},
		"Flower": {
			"AngleOffset": 90,
			"DistanceMult": 0.666,
			"StreamAngleOffset": 90,
			"LongJump": -1,
			"LongJumpMult": 1.2,
			"LongJumpOnEqualPos": true
		},
		"HalfCircle": {
			"RadiusMultiplier": 1,
			"StreamTrigger": 130
		},
		"Spline": {
			"RotationalForce": true,
			"StreamHalfCircle": true,
			"StreamWobble": true,
			"WobbleScale": 0.67
		},
		"Momentum": {
			"SkipStackAngles": false,
			"RestrictAngle": 80,
			"DistanceMult": 0.666,
			"DistanceMultEnd": 0.666
		}
	},
	"Knockout": {
		"Mode": 0,
		"ExcludeMods": "EZHT",
		"HideMods": "",
		"MaxPlayers": 2,
		"BubbleMinimumCombo": 200,
		"RevivePlayersAtEnd": false,
		"MinCursorSize": 12,
		"MaxCursorSize": 14,
		"AddDanser": false,
		"DanserName": "danser"
	}
}

**Comment by IllianDeCube09** [comment]
[settings.txt](https://github.com/Wieku/danser-go/files/5796440/settings.txt)

**Comment by Wieku** [comment]
Missing quote mark here:
![image](https://user-images.githubusercontent.com/5307179/104198322-61b9f780-5426-11eb-9567-013c94e480cc.png)
