### ISSUE TITLE
App tries to play empty replay files

### ISSUE THREAD

**Issue by MostlyGhostlyGaming** [Wieku/danser-go#70]
**Describe the bug**
So during a knockout, the client will just crash without any explanation at all. this only happens in knockout 

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/5823581/danser.log)

**Computer configuration:**
Operating System: Windows 10 Home
CPU: AMD RYZEN 5 4600H
GPU: GTX1650TI

**Comment by Wieku** [comment]
Most probably .osr file has no input data.

**Comment by MostlyGhostlyGaming** [comment]
is there any way for me to fix?
or do i just need to use a different replay file?
