### ISSUE TITLE
fix runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by helpme426** [Wieku/danser-go#72]
I want to knockout Yomi Yori and i have this runtime error 

![image](https://user-images.githubusercontent.com/78611372/107064526-913a0500-6816-11eb-8919-1b4eb2fd19cd.png

https://pastebin.com/3JxGyZaz

Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by Wieku** [comment]
Your settings are broken

**Comment by helpme426** [comment]
woops sorry 4 not responding,
can you send me the settings

**Comment by Wieku** [comment]
What I mean is that you have a mistake in ExcludeMods or HideMods options.

**Comment by helpme426** [comment]
Fixed!
