### ISSUE TITLE
somethings wrong with the files...

### ISSUE THREAD

**Issue by oofyXD** [Wieku/danser-go#75]
**Describe the bug**
the bug is when i open the app it says file not found but the file is RIGHT THERE

**Screenshots**
![image](https://user-images.githubusercontent.com/76968752/109069082-9798ff80-76a5-11eb-9e10-258833c1d2af.png)

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by Wieku** [comment]
Learn how to use Windows and learn how to read readmes
