### ISSUE TITLE
cursor problems

### ISSUE THREAD

**Issue by oofyXD** [Wieku/danser-go#76]
**Describe the bug**
(1) the cursor is not on the screen, while still hitting notes not near the cursor.
(2) cursor turns invisible 

**Screenshots**
![Inkeddanser_2021-03-05_12-51-05_LI](https://user-images.githubusercontent.com/76968752/110172723-6c539600-7db2-11eb-93ed-6302a6708944.jpg)
![Inkeddanser_2021-03-05_12-49-58_LI](https://user-images.githubusercontent.com/76968752/110172729-6d84c300-7db2-11eb-80d2-c6fcf65626d0.jpg)

**Logs**
Put danser.log here.

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i7 8700K
GPU: GTX1080 (if it's a graphics issue)
Sound Card: FiiO E10K (if it's a sound issue)

**Comment by oofyXD** [comment]
and if im stupid jut close it without saying anything. I mean it.

**Comment by Wieku** [comment]
It's actually a valid bug. Will be fixed in 0.5.0

**Comment by Wieku** [comment]
But please next time don't leave my setup in an issue message ;)

**Comment by oofyXD** [comment]
sure thing, im just using my school computer, so i don't know what the setup is

**Comment by Wieku** [comment]
Please read my previous message, it's going to be fixed in 0.5.0 release.
