### ISSUE TITLE
Random Lagspikes while playing maps

### ISSUE THREAD

**Issue by Elektragold** [Wieku/danser-go#83]
**Describe the bug**
Exactly what the title says, I get random lag spikes while playing maps, making my screen freeze for a few seconds. This happens 2-3 times each time I play and is fairly consistent. My FPS stays at a constant 120 until the lag spike hits.

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6241672/danser.log)
[settings - Copy.txt](https://github.com/Wieku/danser-go/files/6241674/settings.-.Copy.txt)

**Computer configuration:**
Operating System: Windows 10
CPU: AMD Ryzen 5
GPU: GTX1050 Ti (if it's a graphics issue)

**Comment by Wieku** [comment]
Have you tried playing with VSync (not FPScap) and without frame limiting? Never experienced an issue like this personally. 

Had a similar issue reported on discord and seems that running danser as an admin helps with those freezes. Probably something is messing with danser's process and threads

**Comment by Elektragold** [comment]
Yeah, the problem seemed to lie in the FPS cap, the lag spikes stopped after setting the cap to 0. Thanks for your help!
