### ISSUE TITLE
Using osu! default skin for unchanged skin elements

### ISSUE THREAD

**Issue by blecbang** [Wieku/danser-go#85]
for people who would like to record in skins that don't change all of the elements, it would be really helpful if there was an option to let unchanged skin elements be filled in from the actual default skin rather than Redd Glass.

**Comment by Wieku** [comment]
Can't do that. I don't want to inflate app's size, second is licensing. Not my problem skin creators are lazy.

**Comment by bbzlazer** [comment]
> for people who would like to record in skins that don't change all of the elements, it would be really helpful if there was an option to let unchanged skin elements be filled in from the actual default skin rather than Redd Glass.

just make a copy of the default skin, you can find a copy on the internet
