### ISSUE TITLE
Invisible sliders on a certain map

### ISSUE THREAD

**Issue by MasterIO02** [Wieku/danser-go#86]
**Describe the bug**
Invisible sliders on https://osu.ppy.sh/beatmapsets/243
Happening with every difficulties, cursordance or replay, any skins

**Screenshots**
![image](https://user-images.githubusercontent.com/40836390/114192328-a4b83800-994d-11eb-9dde-1976a97e67e3.png)

**Logs**
No error in logs

**Computer configuration:**
Bug is happening with any computer

**Comment by Wieku** [comment]
Fixed in dev branch. Keeping open for visibility
