### ISSUE TITLE
Incorrect slider judgement

### ISSUE THREAD

**Issue by PercyDan54** [Wieku/danser-go#87]
**Describe the bug**
Danser shows the replay got a 100, but should be SS

[osu! - Tatsh - IMAGE -MATERIAL- Version 0 [Scorpiour] (2021-04-09) Osu.zip](https://github.com/Wieku/danser-go/files/6286698/osu.-.Tatsh.-.IMAGE.-MATERIAL-.Version.0.Scorpiour.2021-04-09.Osu.zip)

**Screenshots**
https://www.bilibili.com/video/BV1864y1S7Jh?t=380

**Logs**
Not needed

**Computer configuration:**
Not needed

**Comment by Wieku** [comment]
Firstly. Why osu! replay is butchered so much?
Secondly, it's edited to the point even osu can't open it.
![image](https://user-images.githubusercontent.com/5307179/114202494-87886700-9957-11eb-8351-6e11a34824b8.png)

Thirdly, osu! auto exported replays are not even reliable in osu!.

**Comment by PercyDan54** [comment]
1.It's not edited, it's generated by osu [2016 april fools ](https://osu.ppy.sh/wiki/zh/History_of_osu!%2FApril_Fools#2016)version
2. I can still open the replay I attached

**Comment by Wieku** [comment]
It's definitely not pippi from 2016 april fools.

**Comment by Wieku** [comment]
Okay, after some tries it did open the replay, and I still was correct:
![screenshot165](https://user-images.githubusercontent.com/5307179/114206376-93762800-995b-11eb-8004-a56d015f0e0a.png)
