### ISSUE TITLE
CMD Problem

### ISSUE THREAD

**Issue by Hacky-Cat** [Wieku/danser-go#88]
Everytime when I put danser*** < arguments > in cmd it keeps saying "The syntax of the command is incorrect." what can I do to fix this?

**Comment by Wieku** [comment]
you're not supposed to put asterisks...

**Comment by bbzlazer** [comment]
> Everytime when I put danser*** < arguments > in cmd it keeps saying "The syntax of the command is incorrect." what can I do to fix this?

if ur using windows do something like `.\danser.exe -t="Song Name" -d="Difficulty Name"`

**Comment by Wieku** [comment]
> > Everytime when I put danser*** < arguments > in cmd it keeps saying "The syntax of the command is incorrect." what can I do to fix this?
> 
> if ur using windows do something like `.\danser.exe -t="Song Name" -d="Difficulty Name"`

please stop commenting on closed issues.
