### ISSUE TITLE
Spinners incorrectly increment combo color

### ISSUE THREAD

**Issue by alchzh** [Wieku/danser-go#92]
See also #93 on the topic of consistent combo colors.

**Describe the bug**
In Danser, spinners will incorrectly increment the combo counter causing colors to go out of sync with the osu! client. Regardless of the NewCombo flag on the spinner hitobject or the hitobject immediately after it, the combo count goes up by 1 (not 0 or 2).

**Screenshots**
Visible on any map with a spinner when comparing osu! client with Danser. Example can be seen in [this comparison video](https://youtu.be/DfzYR8y0Z0A?t=86&) where the combo colors start out uniform across the three Danser renders and the osu! client recording, but the Danser instances jump one ahead at the 1:24 spinner.

**Comment by Wieku** [comment]
Closing in favor of #93
