### ISSUE TITLE
CMD Error?

### ISSUE THREAD

**Issue by bortigno123** [Wieku/danser-go#94]
**Describe the bug**
When I write the command, various writings come out but then nothing happens.

**Screenshots**
https://cdn.discordapp.com/attachments/813713335886938182/833279050600415233/unknown.png

**Logs**
Put danser.log here.
https://github.com/Wieku/danser-go/files/6330906/danser.log

**Comment by vladaad** [comment]
Weird, it seems to be a problem while parsing https://osu.ppy.sh/beatmapsets/754219#osu/1587910, however I have that same beatmap and it does work without any issues. Could you see if it isn't corrupted by any chance?

**Comment by bortigno123** [comment]
> Weird, it seems to be a problem while parsing https://osu.ppy.sh/beatmapsets/754219#osu/1587910, however I have that same beatmap and it does work without any issues. Could you see if it isn't corrupted by any chance?

I tried to delete the beatmap directly but it always gives me that error
https://github.com/Wieku/danser-go/files/6331155/danser.log
danser.log(danser.log after deleting the map)

**Comment by alchzh** [comment]
It's on this map now: https://osu.ppy.sh/beatmapsets/933984#fruits/1995049

are you doing some weird editing with the text files on your maps? could you upload the `onumi - PERSONALITY (Ascendance) [AJAMEZ'S SALAD].osu` file? It should be in `<your osu! folder>/Songs/933984 onumi - PERSONALITY`

**Comment by bortigno123** [comment]
> It's on this map now: https://osu.ppy.sh/beatmapsets/933984#fruits/1995049
> 
> are you doing some weird editing with the text files on your maps? could you upload the `onumi - PERSONALITY (Ascendance) [AJAMEZ'S SALAD].osu` file? It should be in `<your osu! folder>/Songs/933984 onumi - PERSONALITY`

https://github.com/Wieku/danser-go/files/6331172/osu.map.zip

**Comment by bortigno123** [comment]
I also deleted this beatmap and this time it worked.

**Comment by Wieku** [comment]
![image](https://user-images.githubusercontent.com/5307179/115144699-58a47c00-a04e-11eb-8697-bbc079078d55.png)
Yes it was corrupted
