### ISSUE TITLE
cannot execute binary file on xUbuntu 20.04 64bit

### ISSUE THREAD

**Issue by AtomSnow** [Wieku/danser-go#95]
As i said in title, it does not want to start even with sudo bash or not

After sudo bash danser:
danser: danser: cannot execute binary file

After ./danser:
danser: danser: Permission denied

There may be some problem while building? I am too stupid to build danser for myself

**Comment by alchzh** [comment]
`chmod +x danser`

**Comment by AtomSnow** [comment]
> `chmod +x danser`

Still does not work

**Comment by alchzh** [comment]
`./danser` doesn't work after chmod? are you for some reason on a disk with noexec set?

**Comment by AtomSnow** [comment]
> `./danser` doesn't work after chmod? are you for some reason on a disk with noexec set?

Noexec flag is not set on my drive, i am running this from home/danser and i even did in home/Desktop/dancer

**Comment by alchzh** [comment]
What do you get after `ls -l danser`?

**Comment by AtomSnow** [comment]
> What do you get after `ls -l danser`?

-rw-rw-r-- l snow snow 11140096 may 16 00:30

Im guessing that is fine
Running ffmpeg static works

**Comment by alchzh** [comment]
yeah that still doesn't have executable permissions. are you sure you chmod'd it? maybe try sudo chmod +x danser idk

**Comment by AtomSnow** [comment]
> yeah that still doesn't have executable permissions. are you sure you chmod'd it? maybe try sudo chmod +x danser idk

Still same issue, might drop the executable to some USB Drive later, if i find one and run it
