### ISSUE TITLE
error when trying to record not record

### ISSUE THREAD

**Issue by GDcheeriosYT** [Wieku/danser-go#99]
maybe I am doing something wrong with the parameters but I believe I am doing it correct...

**Logs**[danser.log](https://github.com/Wieku/danser-go/files/6362828/danser.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Ryzen 7 3800x
GPU: RTX 2070 SUPER

**Comment by SEApodEErman** [comment]
Do you have FFmpeg set up in PATH or putting the FFmpeg binary file besides where danser executable at?

**Comment by GDcheeriosYT** [comment]
@SEApodEErman I do not have FFmpeg

**Comment by Wieku** [comment]
Then you need to have one
